dbt_model_generation:
  outputs:
    dev:
      account: HPAFNDX-IW71152
      database: BSL_RAW
      password: Shajahan@snowflake_2002
      role: ACCOUNTADMIN
      schema: DWH_RAW
      threads: 1
      type: snowflake
      user: SHAJAHAN
      warehouse: COMPUTE_WH
  target: dev
