dbt_model_generation:
  outputs:
    dev:
      account: DTJCYHT-WGB03396
      database: DEMO_DB
      password: Shajahan@snowflake_2002
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 1
      type: snowflake
      user: SHAJAHAN
      warehouse: COMPUTE_WH
  target: dev
