{#
------------------------------------------------------------------------
MODEL NAME: dim_product
TARGET TABLE: BSL_MA.DWH_MA.DIM_PRODUCT
SOURCE TABLES: BSL_RAW.DWH_RAW.PRODUCTS
DESCRIPTION: Dimension table for product information with standardized product names, price bands, and data quality flags
PREREQUISITES: Source table BSL_RAW.DWH_RAW.PRODUCTS must exist with required columns
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_product'
) }}

WITH source_data AS (
    SELECT
        product_id,
        product_name,
        price
    FROM {{ source('dwh_raw', 'products') }}
),

transformed AS (
    SELECT
        -- Direct mapping for product_id
        product_id,
        
        -- Title-case product name with trimmed spaces
        TRIM(INITCAP(product_name)) AS product_name,
        
        -- Direct mapping for price with precision
        CAST(price AS NUMBER(10,2)) AS price,
        
        -- Price band categorization
        CASE 
            WHEN price < 50 THEN 'Low'
            WHEN price >= 50 AND price <= 199.99 THEN 'Mid'
            WHEN price >= 200 AND price <= 499.99 THEN 'High'
            WHEN price >= 500 THEN 'Premium'
            ELSE 'Unknown'
        END AS price_band,
        
        -- Flag for review when price is 0
        CASE 
            WHEN price = 0 THEN 'Price requires review - zero value detected'
            ELSE NULL
        END AS review_notes
        
    FROM source_data
)

SELECT * FROM transformed