{#
------------------------------------------------------------------------
MODEL NAME    : dim_supplier
TARGET TABLE  : bsl_ma.dwh_ma.dim_supplier
SOURCE TABLES : bsl_raw.dwh_raw.suppliers
DESCRIPTION   : Dimension table for supplier information with data quality transformations
PREREQUISITES : Source table bsl_raw.dwh_raw.suppliers must exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_supplier'
) }}

WITH source_data AS (
    SELECT
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag
    FROM {{ source('dwh_raw', 'suppliers') }}
),

transformed AS (
    SELECT
        -- Direct mapping for supplier_id
        supplier_id,
        
        -- Trim and title-case for supplier_name
        INITCAP(TRIM(supplier_name)) AS supplier_name,
        
        -- Lowercase email with validation - set null if invalid pattern
        CASE 
            WHEN contact_email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' 
            THEN LOWER(contact_email)
            ELSE NULL
        END AS contact_email,
        
        -- Uppercase country
        UPPER(country) AS country,
        
        -- Direct mapping for active_flag with default false for null values
        COALESCE(active_flag, FALSE) AS is_active
        
    FROM source_data
)

SELECT * FROM transformed