{#
------------------------------------------------------------------------
MODEL NAME: dim_product
TARGET TABLE: BSL_MA.DWH_MA.DIM_PRODUCT
SOURCE TABLES: BSL_RAW.DWH_RAW.PRODUCTS
DESCRIPTION: Product dimension table that transforms raw product data with price banding and data quality enhancements
PREREQUISITES: Source table BSL_RAW.DWH_RAW.PRODUCTS must be available
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

WITH source_data AS (
    SELECT 
        product_id,
        product_name,
        price
    FROM {{ source('dwh_raw', 'products') }}
),

transformed_data AS (
    SELECT 
        -- Direct mapping with alias
        product_id AS product_id,
        
        -- Title-case product name with trimmed spaces
        INITCAP(TRIM(REGEXP_REPLACE(product_name, '\\s+', ' '))) AS product_name,
        
        -- Direct price mapping
        price AS price,
        
        -- Price banding logic
        CASE 
            WHEN price < 50 THEN 'Low'
            WHEN price >= 50 AND price <= 199.99 THEN 'Mid'
            WHEN price >= 200 AND price <= 499.99 THEN 'High'
            WHEN price >= 500 THEN 'Premium'
            ELSE 'Unknown'
        END AS price_band
        
    FROM source_data
)

SELECT 
    product_id,
    product_name,
    price,
    price_band
FROM transformed_data