{#
------------------------------------------------------------------------
MODEL NAME: dim_category
TARGET TABLE: bsl_ma.dwh_ma.dim_category
SOURCE TABLES: bsl_raw.dwh_raw.categories
DESCRIPTION: Dimension table for product categories with hierarchical path structure up to 2 levels
PREREQUISITES: Source table categories must exist in dwh_raw schema
PARAMETER: None
AUTHOUR: AI Generated by Shajahan
CREATED DATE: 2025-01-11 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_category'
) }}

WITH source_data AS (
    SELECT
        c.category_id,
        c.category_name,
        c.parent_category_id,
        c.is_active
    FROM {{ source('dwh_raw', 'categories') }} c
),

parent_categories AS (
    SELECT
        p.category_id as parent_id,
        p.category_name as parent_category_name
    FROM {{ source('dwh_raw', 'categories') }} p
),

transformed AS (
    SELECT
        s.category_id,
        TRIM(INITCAP(s.category_name)) as category_name,
        s.parent_category_id,
        CASE 
            WHEN s.parent_category_id IS NOT NULL AND p.parent_category_name IS NOT NULL 
            THEN p.parent_category_name || ' > ' || TRIM(INITCAP(s.category_name))
            ELSE TRIM(INITCAP(s.category_name))
        END as category_path,
        COALESCE(s.is_active, TRUE) as is_active
    FROM source_data s
    LEFT JOIN parent_categories p ON s.parent_category_id = p.parent_id
)

SELECT * FROM transformed