{#
------------------------------------------------------------------------
MODEL NAME: dim_category
TARGET TABLE: BSL_MA.DWH_MA.DIM_CATEGORY
SOURCE TABLES: BSL_RAW.DWH_RAW.CATEGORIES
DESCRIPTION: Dimension table for product categories with hierarchical path structure up to 2 levels
PREREQUISITES: Source table BSL_RAW.DWH_RAW.CATEGORIES must be available
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

WITH category_base AS (
    SELECT 
        category_id,
        TRIM(INITCAP(category_name)) AS category_name,
        parent_category_id,
        COALESCE(is_active, TRUE) AS is_active
    FROM {{ source('dwh_raw', 'categories') }}
),

parent_categories AS (
    SELECT 
        category_id,
        TRIM(INITCAP(category_name)) AS parent_category_name
    FROM {{ source('dwh_raw', 'categories') }}
),

final AS (
    SELECT 
        cb.category_id,
        cb.category_name,
        cb.parent_category_id,
        -- Build category path up to 2 levels
        CASE 
            WHEN cb.parent_category_id IS NOT NULL AND pc.parent_category_name IS NOT NULL 
            THEN pc.parent_category_name || ' > ' || cb.category_name
            ELSE cb.category_name
        END AS category_path,
        cb.is_active
    FROM category_base cb
    LEFT JOIN parent_categories pc 
        ON cb.parent_category_id = pc.category_id
)

SELECT * FROM final