{#
------------------------------------------------------------------------
MODEL NAME: dim_supplier
TARGET TABLE: BSL_MA.DWH_MA.DIM_SUPPLIER
SOURCE TABLES: BSL_RAW.DWH_RAW.SUPPLIERS
DESCRIPTION: Dimension table for suppliers with cleaned and standardized supplier information including contact details and status flags
PREREQUISITES: Source table BSL_RAW.DWH_RAW.SUPPLIERS must be available and populated
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

SELECT
    -- Direct mapping of supplier ID
    supplier_id,
    
    -- Trim and title-case supplier name
    INITCAP(TRIM(supplier_name)) AS supplier_name,
    
    -- Lowercase email with validation - set null if invalid pattern
    CASE 
        WHEN contact_email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' 
        THEN LOWER(contact_email)
        ELSE NULL
    END AS contact_email,
    
    -- Uppercase country
    UPPER(country) AS country,
    
    -- Direct mapping with null handling - default false if null
    COALESCE(active_flag, FALSE) AS is_active

FROM {{ source('dwh_raw', 'suppliers') }}