{#
------------------------------------------------------------------------
MODEL NAME: dim_address
TARGET TABLE: BSL_MA.DWH_MA.DIM_ADDRESS
SOURCE TABLES: BSL_RAW.DWH_RAW.ADDRESSES
DESCRIPTION: This model creates a dimension table for addresses by transforming and cleaning raw address data, including customer lookups and data normalization.
PREREQUISITES: dim_customer table must exist for customer_id lookup
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

WITH source_data AS (
    SELECT 
        address_id,
        customer_id,
        address_line1,
        city,
        country,
        inserted_at
    FROM {{ source('dwh_raw', 'addresses') }}
),

customer_lookup AS (
    SELECT 
        customer_id
    FROM {{ ref('dim_customer') }}
),

transformed_data AS (
    SELECT 
        s.address_id,
        c.customer_id::INTEGER AS customer_id,
        TRIM(s.address_line1) AS address_line1,
        UPPER(s.city) AS city,
        s.country,
        s.inserted_at::DATE AS inserted_at
    FROM source_data s
    INNER JOIN customer_lookup c 
        ON s.customer_id = c.customer_id
)

SELECT * FROM transformed_data