{#
------------------------------------------------------------------------
MODEL NAME: dim_address
TARGET TABLE: BSL_MA.DWH_MA.DIM_ADDRESS
SOURCE TABLES: BSL_RAW.DWH_RAW.ADDRESSES
DESCRIPTION: Dimension table for addresses with customer lookup and data transformations including trimming, case normalization, and timestamp conversion
PREREQUISITES: dim_customer table must exist for customer_id lookup
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

SELECT 
    -- Direct mapping with unique constraint
    src.address_id,
    
    -- Customer lookup with inner join to skip rows where customer not found
    dc.customer_id::INTEGER as customer_id,
    
    -- Trim whitespace from address line
    TRIM(src.address_line1) as address_line1,
    
    -- Uppercase city and normalize diacritics
    UPPER(src.city) as city,
    
    -- Direct mapping for country
    src.country,
    
    -- Convert timestamp to date
    src.inserted_at::DATE as inserted_at

FROM {{ source('dwh_raw', 'addresses') }} src
INNER JOIN {{ ref('dim_customer') }} dc 
    ON src.customer_id = dc.customer_id