{#
------------------------------------------------------------------------
MODEL NAME: dim_customer
TARGET TABLE: bsl_ma.dwh_ma.dim_customer
SOURCE TABLES: bsl_raw.dwh_raw.customers
DESCRIPTION: Customer master dimension table that consolidates customer information with derived attributes like customer tier based on spending patterns
PREREQUISITES: Source table bsl_raw.dwh_raw.customers must be available
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with customer_orders as (
    select 
        customer_id,
        sum(order_amount) as total_order_amount_365d
    from {{ source('dwh_raw', 'orders') }}
    where order_date >= current_date - 365
    group by customer_id
),

customer_base as (
    select 
        customer_id,
        first_name,
        last_name,
        email,
        inserted_at
    from {{ source('dwh_raw', 'customers') }}
    where customer_id is not null 
        and trim(customer_id) != ''
        and customer_id != 'NULL'
),

final as (
    select 
        -- Generate surrogate key from customer_id
        {{ dbt_utils.generate_surrogate_key(['cb.customer_id']) }} as customer_sk,
        
        -- Direct mapping of customer_id
        cb.customer_id,
        
        -- Trim and upper-case first name
        upper(trim(cb.first_name)) as first_name,
        
        -- Trim and upper-case last name  
        upper(trim(cb.last_name)) as last_name,
        
        -- Lowercase email for consistency with pattern validation
        case 
            when cb.email is null or trim(cb.email) = '' then null
            when cb.email regexp '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' then lower(trim(cb.email))
            else null
        end as email,
        
        -- Convert timestamp to date, default to current_date if null
        coalesce(cb.inserted_at::date, current_date) as customer_since_date,
        
        -- Derive spending tier based on total order amount in last 365 days
        case 
            when coalesce(co.total_order_amount_365d, 0) >= 1000 then 'GOLD'
            when coalesce(co.total_order_amount_365d, 0) >= 500 then 'SILVER'
            else 'BRONZE'
        end as customer_tier
        
    from customer_base cb
    left join customer_orders co on cb.customer_id = co.customer_id
)

select * from final