{#
------------------------------------------------------------------------
MODEL NAME: dim_product
TARGET TABLE: BSL_MA.DWH_MA.DIM_PRODUCT
SOURCE TABLES: BSL_RAW.DWH_RAW.PRODUCTS
DESCRIPTION: Product dimension table that transforms raw product data with category lookups, price banding, and data quality validations
PREREQUISITES: dim_category table must exist for category lookups
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

SELECT 
    -- Direct mapping with unique constraint
    product_id,
    
    -- Title-case product name with trimmed spaces
    INITCAP(TRIM(REGEXP_REPLACE(product_name, '\\s+', ' '))) AS product_name,
    
    -- Category lookup with fallback to 0 for missing categories
    COALESCE(dc.category_id, 0) AS category_id,
    
    -- Direct price mapping with precision
    CAST(price AS NUMBER(10,2)) AS price,
    
    -- Price banding logic
    CASE 
        WHEN price < 50 THEN 'Low'
        WHEN price >= 50 AND price <= 199.99 THEN 'Mid'
        WHEN price >= 200 AND price <= 499.99 THEN 'High'
        WHEN price >= 500 THEN 'Premium'
        ELSE 'Unknown'
    END AS price_band,
    
    -- Data quality notes for zero prices
    CASE 
        WHEN price = 0 THEN 'Price flagged for review - zero value detected'
        ELSE NULL
    END AS data_quality_notes

FROM {{ source('dwh_raw', 'products') }} p
LEFT JOIN {{ ref('dim_category') }} dc 
    ON p.category_id = dc.category_id