{#
------------------------------------------------------------------------
MODEL NAME: DIM_PRODUCT
TARGET TABLE: BSL_MA.DWH_MA.DIM_PRODUCT
SOURCE TABLES: BSL_RAW.DWH_RAW.PRODUCTS
DESCRIPTION: Product master dimension table that transforms raw product data with surrogate key generation, price banding, and category lookups
PREREQUISITES: DIM_CATEGORY table must exist for category lookups
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

WITH source_data AS (
    SELECT 
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY_ID,
        PRICE
    FROM {{ source('dwh_raw', 'products') }}
    WHERE PRICE IS NOT NULL 
      AND PRICE >= 0
),

category_lookup AS (
    SELECT 
        CATEGORY_ID,
        CATEGORY_SK
    FROM {{ ref('dim_category') }}
),

transformed AS (
    SELECT 
        -- Generate surrogate key from PRODUCT_ID
        {{ dbt_utils.generate_surrogate_key(['PRODUCT_ID']) }} AS PRODUCT_SK,
        
        -- Direct mapping of PRODUCT_ID
        s.PRODUCT_ID,
        
        -- Title-case product name and trim excessive spaces
        INITCAP(TRIM(REGEXP_REPLACE(s.PRODUCT_NAME, '\\s+', ' '))) AS PRODUCT_NAME,
        
        -- Lookup CATEGORY_SK, set to 0 if missing
        COALESCE(c.CATEGORY_SK, 0) AS CATEGORY_SK,
        
        -- Direct mapping of PRICE
        CAST(s.PRICE AS NUMBER(10,2)) AS PRICE,
        
        -- Price banding logic
        CASE 
            WHEN s.PRICE < 50 THEN 'Low'
            WHEN s.PRICE >= 50 AND s.PRICE <= 199.99 THEN 'Mid'
            WHEN s.PRICE >= 200 AND s.PRICE <= 499.99 THEN 'High'
            WHEN s.PRICE >= 500 THEN 'Premium'
            ELSE 'Unknown'
        END AS PRICE_BAND,
        
        -- Flag for review when PRICE = 0
        CASE 
            WHEN s.PRICE = 0 THEN 'Price is zero - flagged for review'
            ELSE NULL
        END AS REVIEW_NOTES
        
    FROM source_data s
    LEFT JOIN category_lookup c
        ON s.CATEGORY_ID = c.CATEGORY_ID
)

SELECT * FROM transformed