{#
------------------------------------------------------------------------
MODEL NAME: dim_customer
TARGET TABLE: bsl_ma.dwh_ma.dim_customer
SOURCE TABLES: bsl_raw.dwh_raw.customers, bsl_raw.dwh_raw.fact_order
DESCRIPTION: Customer dimension table that transforms raw customer data with cleansed names, validated emails, and derived customer tiers based on spending patterns
PREREQUISITES: Source tables bsl_raw.dwh_raw.customers and bsl_raw.dwh_raw.fact_order must be available
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

WITH customer_orders AS (
    SELECT 
        customer_id,
        SUM(order_amount) AS total_order_amount_365_days
    FROM {{ source('dwh_raw', 'fact_order') }}
    WHERE order_date >= DATEADD('day', -365, CURRENT_DATE())
    GROUP BY customer_id
),

customer_tier_logic AS (
    SELECT 
        c.customer_id,
        TRIM(UPPER(c.first_name)) AS first_name,
        TRIM(UPPER(c.last_name)) AS last_name,
        CASE 
            WHEN REGEXP_LIKE(LOWER(TRIM(c.email)), '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$') 
            THEN LOWER(TRIM(c.email))
            ELSE NULL 
        END AS email,
        CASE 
            WHEN c.inserted_at IS NULL THEN CURRENT_DATE()
            ELSE DATE(c.inserted_at)
        END AS customer_since_date,
        CASE 
            WHEN co.total_order_amount_365_days >= 1000 THEN 'Gold'
            WHEN co.total_order_amount_365_days >= 500 THEN 'Silver'
            ELSE 'Bronze'
        END AS customer_tier
    FROM {{ source('dwh_raw', 'customers') }} c
    LEFT JOIN customer_orders co ON c.customer_id = co.customer_id
)

SELECT 
    customer_id,
    first_name,
    last_name,
    email,
    customer_since_date,
    customer_tier
FROM customer_tier_logic