{#
------------------------------------------------------------------------
MODEL NAME: dim_customer
TARGET TABLE: BSL_MA.DWH_MA.DIM_CUSTOMER
SOURCE TABLES: BSL_RAW.DWH_RAW.CUSTOMERS, BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION: Customer dimension table with customer details and derived spending tier based on order history
PREREQUISITES: Source tables customers and orders must be available in dwh_raw schema
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    schema = 'dwh_ma',
    alias = 'dim_customer'
) }}

WITH customers_source AS (
    SELECT
        customer_id,
        first_name,
        last_name,
        email,
        inserted_at
    FROM {{ source('dwh_raw', 'customers') }}
),

orders_source AS (
    SELECT
        customer_id,
        total_amount,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
),

customer_spending AS (
    SELECT
        customer_id,
        SUM(total_amount) AS total_spending_365_days
    FROM orders_source
    WHERE order_date >= DATEADD('day', -365, CURRENT_DATE())
    GROUP BY customer_id
),

transformed AS (
    SELECT
        c.customer_id,
        UPPER(TRIM(c.first_name)) AS first_name,
        UPPER(TRIM(c.last_name)) AS last_name,
        CASE 
            WHEN REGEXP_LIKE(LOWER(TRIM(c.email)), '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')
            THEN LOWER(TRIM(c.email))
            ELSE NULL
        END AS email,
        COALESCE(DATE(c.inserted_at), CURRENT_DATE()) AS customer_since_date,
        CASE 
            WHEN COALESCE(cs.total_spending_365_days, 0) >= 1000 THEN 'Gold'
            WHEN COALESCE(cs.total_spending_365_days, 0) >= 500 THEN 'Silver'
            ELSE 'Bronze'
        END AS customer_tier
    FROM customers_source c
    LEFT JOIN customer_spending cs ON c.customer_id = cs.customer_id
)

SELECT * FROM transformed