{#
------------------------------------------------------------------------
MODEL NAME: dim_supplier
TARGET TABLE: bsl_ma.dwh_ma.dim_supplier
SOURCE TABLES: bsl_raw.dwh_raw.suppliers
DESCRIPTION: Dimension table for supplier data with data quality transformations including email validation, name formatting, and country standardization
PREREQUISITES: Source table bsl_raw.dwh_raw.suppliers must exist and be accessible
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    schema = 'dwh_ma',
    alias = 'dim_supplier'
) }}

WITH source_data AS (
    SELECT
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag
    FROM {{ source('dwh_raw', 'suppliers') }}
),

transformed AS (
    SELECT
        supplier_id,
        INITCAP(TRIM(supplier_name)) AS supplier_name,
        CASE 
            WHEN REGEXP_LIKE(LOWER(TRIM(contact_email)), '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')
            THEN LOWER(TRIM(contact_email))
            ELSE NULL
        END AS contact_email,
        UPPER(TRIM(country)) AS country,
        COALESCE(active_flag, FALSE) AS is_active
    FROM source_data
)

SELECT * FROM transformed;