{#
------------------------------------------------------------------------
MODEL NAME: dim_customer
TARGET TABLE: bsl_ma.dwh_ma.dim_customer
SOURCE TABLES: bsl_raw.dwh_raw.customers, bsl_raw.dwh_raw.fact_order
DESCRIPTION: Customer dimension table that transforms raw customer data with proper formatting, email validation, customer tier derivation based on order history, and data quality checks
PREREQUISITES: Source tables bsl_raw.dwh_raw.customers and bsl_raw.dwh_raw.fact_order must be available
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with customer_orders as (
    select 
        customer_id,
        sum(order_amount) as total_order_amount_365d
    from {{ source('dwh_raw', 'fact_order') }}
    where order_date >= dateadd('day', -365, current_date())
    group by customer_id
),

customer_tiers as (
    select 
        customer_id,
        case 
            when total_order_amount_365d >= 1000 then 'Gold'
            when total_order_amount_365d >= 500 then 'Silver'
            else 'Bronze'
        end as customer_tier
    from customer_orders
),

base_customers as (
    select
        customer_id,
        -- Trim and uppercase first name, strip leading/trailing spaces
        upper(trim(first_name)) as first_name,
        -- Trim and uppercase last name
        upper(trim(last_name)) as last_name,
        -- Lowercase email for consistency with basic pattern validation
        case 
            when email is not null 
                and email like '%_@_%._%' 
                and length(email) > 5
            then lower(trim(email))
            else null
        end as email,
        -- Convert timestamp to date, default to current_date if null
        coalesce(date(inserted_at), current_date()) as customer_since_date,
        -- Add data quality flag for email issues
        case 
            when email is not null 
                and not (email like '%_@_%._%' and length(email) > 5)
            then 'Invalid email format'
            else null
        end as data_quality_issue
    from {{ source('dwh_raw', 'customers') }}
)

select 
    bc.customer_id,
    bc.first_name,
    bc.last_name,
    bc.email,
    bc.customer_since_date,
    -- Default to Bronze if no tier found (no orders)
    coalesce(ct.customer_tier, 'Bronze') as customer_tier,
    bc.data_quality_issue
from base_customers bc
left join customer_tiers ct 
    on bc.customer_id = ct.customer_id