{#
------------------------------------------------------------------------
MODEL NAME: dim_category
TARGET TABLE: BSL_MA.DWH_MA.DIM_CATEGORY
SOURCE TABLES: BSL_RAW.DWH_RAW.CATEGORIES
DESCRIPTION: Dimension table for product categories with hierarchical path structure up to 2 levels
PREREQUISITES: Source table BSL_RAW.DWH_RAW.CATEGORIES must be available
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_categories as (
    select 
        category_id,
        category_name,
        parent_category_id,
        is_active
    from {{ source('dwh_raw', 'categories') }}
),

parent_categories as (
    select 
        category_id as parent_id,
        trim(initcap(category_name)) as parent_category_name
    from {{ source('dwh_raw', 'categories') }}
),

transformed_categories as (
    select 
        sc.category_id,
        trim(initcap(sc.category_name)) as category_name,
        sc.parent_category_id,
        case 
            when sc.parent_category_id is not null and pc.parent_category_name is not null 
            then pc.parent_category_name || ' > ' || trim(initcap(sc.category_name))
            else trim(initcap(sc.category_name))
        end as category_path,
        coalesce(sc.is_active, true) as is_active
    from source_categories sc
    left join parent_categories pc 
        on sc.parent_category_id = pc.parent_id
)

select 
    category_id,
    category_name,
    parent_category_id,
    category_path,
    is_active
from transformed_categories