{#
------------------------------------------------------------------------
MODEL NAME: dim_category
TARGET TABLE: bsl_ma.dwh_ma.dim_category
SOURCE TABLES: bsl_raw.dwh_raw.categories
DESCRIPTION: Dimension table for product categories with hierarchical path structure up to 2 levels
PREREQUISITES: Source table categories must exist in dwh_raw schema
PARAMETER: None
AUTHOUR: AI Generated by Shajahan
CREATED DATE: 12 November 2025 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    alias = 'dim_category'
) }}

WITH source_data AS (
    SELECT
        src.category_id,
        src.category_name,
        src.parent_category_id,
        src.is_active
    FROM {{ source('dwh_raw', 'categories') }} src
),

parent_categories AS (
    SELECT
        src.category_id,
        src.category_name,
        src.parent_category_id,
        src.is_active
    FROM {{ source('dwh_raw', 'categories') }} src
),

transformed AS (
    SELECT
        src.category_id,
        TRIM(INITCAP(src.category_name)) AS category_name,
        src.parent_category_id,
        CASE 
            WHEN parent.category_name IS NOT NULL THEN 
                TRIM(INITCAP(parent.category_name)) || ' > ' || TRIM(INITCAP(src.category_name))
            ELSE 
                TRIM(INITCAP(src.category_name))
        END AS category_path,
        COALESCE(src.is_active, TRUE) AS is_active
    FROM source_data src
    LEFT JOIN parent_categories parent
        ON src.parent_category_id = parent.category_id
)

SELECT * FROM transformed