{#
------------------------------------------------------------------------
MODEL NAME: dim_customer
TARGET TABLE: bsl_ma.dwh_ma.dim_customer
SOURCE TABLES: bsl_raw.dwh_raw.customers, bsl_raw.dwh_raw.orders
DESCRIPTION: Customer dimension table with derived customer tier based on spending patterns
PREREQUISITES: Source tables customers and orders must be available
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'view'
) }}

WITH customers_source AS (
    SELECT
        customer_id,
        first_name,
        last_name,
        email,
        inserted_at
    FROM {{ source('dwh_raw', 'customers') }}
),

orders_source AS (
    SELECT
        customer_id,
        order_id,
        total_amount,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
),

customer_spending AS (
    SELECT
        o.customer_id,
        SUM(o.total_amount) AS total_spending_365_days
    FROM orders_source o
    WHERE o.order_date >= DATEADD(day, -365, CURRENT_DATE())
    GROUP BY o.customer_id
),

transformed AS (
    SELECT
        c.customer_id,
        UPPER(TRIM(c.first_name)) AS first_name,
        UPPER(TRIM(c.last_name)) AS last_name,
        CASE 
            WHEN REGEXP_LIKE(LOWER(TRIM(c.email)), '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')
            THEN LOWER(TRIM(c.email))
            ELSE NULL
        END AS email,
        COALESCE(DATE(c.inserted_at), CURRENT_DATE()) AS customer_since_date,
        CASE 
            WHEN cs.total_spending_365_days >= 1000 THEN 'Gold'
            WHEN cs.total_spending_365_days >= 500 AND cs.total_spending_365_days < 1000 THEN 'Silver'
            ELSE 'Bronze'
        END AS customer_tier
    FROM customers_source c
    LEFT JOIN customer_spending cs ON c.customer_id = cs.customer_id
)

SELECT * FROM transformed