{#
------------------------------------------------------------------------
MODEL NAME: dim_customer
TARGET TABLE: bsl_ma.dwh_ma.dim_customer
SOURCE TABLES: bsl_raw.dwh_raw.customers, bsl_raw.dwh_raw.orders
DESCRIPTION: Customer dimension table with derived customer tier based on spending patterns
PREREQUISITES: Source tables customers and orders must be available
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'view'
) }}

WITH customers_source AS (
    SELECT
        customer_id,
        first_name,
        last_name,
        email,
        inserted_at
    FROM {{ source('dwh_raw', 'customers') }}
),

orders_source AS (
    SELECT
        customer_id,
        total_amount,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
    WHERE order_date >= CURRENT_DATE - 365
),

customer_spending AS (
    SELECT
        o.customer_id,
        SUM(o.total_amount) AS total_spending_365_days
    FROM orders_source o
    GROUP BY o.customer_id
),

transformed AS (
    SELECT
        c.customer_id,
        UPPER(TRIM(c.first_name)) AS first_name,
        UPPER(TRIM(c.last_name)) AS last_name,
        CASE 
            WHEN c.email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' 
            THEN LOWER(c.email)
            ELSE NULL
        END AS email,
        CASE 
            WHEN c.inserted_at IS NULL 
            THEN CURRENT_DATE()
            ELSE DATE(c.inserted_at)
        END AS customer_since_date,
        CASE 
            WHEN COALESCE(cs.total_spending_365_days, 0) >= 1000 THEN 'Gold'
            WHEN COALESCE(cs.total_spending_365_days, 0) >= 500 THEN 'Silver'
            ELSE 'Bronze'
        END AS customer_tier
    FROM customers_source c
    LEFT JOIN customer_spending cs ON c.customer_id = cs.customer_id
)

SELECT * FROM transformed