{#
------------------------------------------------------------------------
MODEL NAME: dim_product
TARGET TABLE: BSL_MA.DWH_MA.DIM_PRODUCT
SOURCE TABLES: BSL_RAW.DWH_RAW.PRODUCTS
DESCRIPTION: Product master dimension table that transforms raw product data into a structured dimensional model with surrogate keys, standardized naming, price banding, and category lookups.
PREREQUISITES: dim_category table must exist for category lookups
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

WITH source_data AS (
    SELECT 
        product_id,
        product_name,
        category_id,
        price
    FROM {{ source('dwh_raw', 'products') }}
    WHERE price IS NOT NULL 
      AND price >= 0
),

category_lookup AS (
    SELECT 
        category_id,
        category_sk
    FROM {{ ref('dim_category') }}
),

transformed_data AS (
    SELECT
        -- Generate surrogate key from product_id
        {{ dbt_utils.generate_surrogate_key(['s.product_id']) }} AS product_sk,
        
        -- Direct mapping of product_id
        s.product_id,
        
        -- Title-case product name and trim excessive spaces
        INITCAP(TRIM(REGEXP_REPLACE(s.product_name, '\\s+', ' '))) AS product_name,
        
        -- Lookup category_sk, set to 0 if missing
        COALESCE(c.category_sk, 0) AS category_sk,
        
        -- Direct mapping of price
        CAST(s.price AS NUMBER(10,2)) AS price,
        
        -- Price banding logic
        CASE 
            WHEN s.price < 50 THEN 'Low'
            WHEN s.price >= 50 AND s.price <= 199.99 THEN 'Mid'
            WHEN s.price >= 200 AND s.price <= 499.99 THEN 'High'
            WHEN s.price >= 500 THEN 'Premium'
        END AS price_band,
        
        -- Flag for review if price = 0
        CASE 
            WHEN s.price = 0 THEN 'Price is zero - requires review'
            ELSE NULL
        END AS notes
        
    FROM source_data s
    LEFT JOIN category_lookup c
        ON s.category_id = c.category_id
)

SELECT * FROM transformed_data