{#
------------------------------------------------------------------------
MODEL NAME    : dim_supplier
TARGET TABLE  : bsl_ma.dwh_ma.dim_supplier
SOURCE TABLES : bsl_raw.dwh_raw.suppliers
DESCRIPTION   : Dimension table for supplier master data with data quality 
                transformations including email validation, name formatting,
                and country standardization
PREREQUISITES : Source table bsl_raw.dwh_raw.suppliers must exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan
CREATED DATE  : 2025-01-27 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_data AS (
    SELECT
        supplier_id,
        supplier_name,
        contact_email,
        country,
        active_flag
    FROM {{ source('dwh_raw', 'suppliers') }}
),

transformed AS (
    SELECT
        supplier_data.supplier_id,
        INITCAP(TRIM(supplier_data.supplier_name)) AS supplier_name,
        CASE 
            WHEN supplier_data.contact_email RLIKE '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' 
            THEN LOWER(supplier_data.contact_email)
            ELSE NULL
        END AS contact_email,
        UPPER(supplier_data.country) AS country,
        COALESCE(supplier_data.active_flag, FALSE) AS is_active
    FROM source_data AS supplier_data
)

SELECT * FROM transformed