{#
------------------------------------------------------------------------
MODEL NAME: DIM_SUPPLIER
TARGET TABLE: BSL_MA.DWH_MA.DIM_SUPPLIER
SOURCE TABLES: BSL_RAW.DWH_RAW.SUPPLIER
DESCRIPTION: Supplier master dimension table that transforms raw supplier data into a clean dimensional model with surrogate keys and standardized formatting
PREREQUISITES: Source table BSL_RAW.DWH_RAW.SUPPLIER must exist and contain supplier master data
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

WITH source_data AS (
    SELECT 
        SUPPLIER_ID,
        SUPPLIER_NAME,
        CONTACT_EMAIL,
        COUNTRY,
        ACTIVE_FLAG
    FROM {{ source('BSL_RAW', 'SUPPLIER') }}
),

transformed_data AS (
    SELECT
        -- Generate surrogate key from SUPPLIER_ID
        {{ dbt_utils.generate_surrogate_key(['SUPPLIER_ID']) }} AS SUPPLIER_SK,
        
        -- Direct mapping of SUPPLIER_ID
        SUPPLIER_ID,
        
        -- Trim and title-case supplier name
        INITCAP(TRIM(SUPPLIER_NAME)) AS SUPPLIER_NAME,
        
        -- Lowercase email and validate pattern, set null if invalid
        CASE 
            WHEN CONTACT_EMAIL IS NOT NULL 
                AND REGEXP_LIKE(LOWER(TRIM(CONTACT_EMAIL)), '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')
            THEN LOWER(TRIM(CONTACT_EMAIL))
            ELSE NULL
        END AS CONTACT_EMAIL,
        
        -- Uppercase country
        UPPER(TRIM(COUNTRY)) AS COUNTRY,
        
        -- Direct mapping with default false for null values
        COALESCE(ACTIVE_FLAG, FALSE) AS IS_ACTIVE
        
    FROM source_data
)

SELECT * FROM transformed_data