{#
------------------------------------------------------------------------
MODEL NAME: dim_address
TARGET TABLE: bsl_ma.dwh_ma.dim_address
SOURCE TABLES: bsl_raw.dwh_raw.addresses
DESCRIPTION: Dimension table for address information with customer lookup validation and data transformations
PREREQUISITES: dim_customer table must exist for customer_id validation
PARAMETER: None
AUTHOUR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_data AS (
    SELECT
        a.address_id,
        a.customer_id,
        a.address_line1,
        a.city,
        a.country,
        a.inserted_at
    FROM {{ source('dwh_raw', 'addresses') }} a
),

customer_lookup AS (
    SELECT
        c.customer_id
    FROM {{ ref('dim_customer') }} c
),

validated_addresses AS (
    SELECT
        s.address_id,
        s.customer_id,
        s.address_line1,
        s.city,
        s.country,
        s.inserted_at
    FROM source_data s
    INNER JOIN customer_lookup c
        ON s.customer_id = c.customer_id
),

transformed AS (
    SELECT
        address_id,
        customer_id,
        TRIM(address_line1) AS address_line1,
        UPPER(city) AS city,
        country,
        DATE(inserted_at) AS inserted_at
    FROM validated_addresses
)

SELECT * FROM transformed