{#
------------------------------------------------------------------------
MODEL NAME: DIM_CATEGORY
TARGET TABLE: BSL_MA.DWH_MA.DIM_CATEGORY
SOURCE TABLES: BSL_RAW.DWH_RAW.CATEGORY
DESCRIPTION: Product category hierarchy dimension table with surrogate keys and category path generation
PREREQUISITES: Source table BSL_RAW.DWH_RAW.CATEGORY must exist with required columns
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

WITH source_data AS (
    SELECT 
        CATEGORY_ID,
        TRIM(INITCAP(CATEGORY_NAME)) AS CATEGORY_NAME,
        PARENT_CATEGORY_ID,
        COALESCE(IS_ACTIVE, TRUE) AS IS_ACTIVE
    FROM {{ source('BSL_RAW', 'CATEGORY') }}
),

parent_lookup AS (
    SELECT 
        s.CATEGORY_ID,
        s.CATEGORY_NAME,
        s.PARENT_CATEGORY_ID,
        s.IS_ACTIVE,
        p.CATEGORY_NAME AS PARENT_CATEGORY_NAME
    FROM source_data s
    LEFT JOIN source_data p 
        ON s.PARENT_CATEGORY_ID = p.CATEGORY_ID
),

final AS (
    SELECT 
        -- Generate surrogate key from CATEGORY_ID
        {{ dbt_utils.generate_surrogate_key(['CATEGORY_ID']) }} AS CATEGORY_SK,
        
        -- Direct mapping of CATEGORY_ID
        CATEGORY_ID,
        
        -- Trim and title-case CATEGORY_NAME
        CATEGORY_NAME,
        
        -- Direct mapping of PARENT_CATEGORY_ID (may be null for root categories)
        PARENT_CATEGORY_ID,
        
        -- Lookup parent CATEGORY_SK using PARENT_CATEGORY_ID
        CASE 
            WHEN PARENT_CATEGORY_ID IS NOT NULL 
            THEN {{ dbt_utils.generate_surrogate_key(['PARENT_CATEGORY_ID']) }}
            ELSE NULL 
        END AS PARENT_CATEGORY_SK,
        
        -- Build category path up to 2 levels: PARENT_CATEGORY_NAME > CATEGORY_NAME
        CASE 
            WHEN PARENT_CATEGORY_NAME IS NOT NULL 
            THEN PARENT_CATEGORY_NAME || ' > ' || CATEGORY_NAME
            ELSE CATEGORY_NAME 
        END AS CATEGORY_PATH,
        
        -- Direct mapping of IS_ACTIVE with default true if null
        IS_ACTIVE
        
    FROM parent_lookup
)

SELECT * FROM final