{#
------------------------------------------------------------------------
MODEL NAME: dim_address
TARGET TABLE: BSL_MA.DWH_MA.DIM_ADDRESS
SOURCE TABLES: BSL_RAW.DWH_RAW.ADDRESSES
DESCRIPTION: This model transforms raw address data into a dimensional table for analytics. It performs data cleansing, normalization, and customer lookup validation.
PREREQUISITES: dim_customer table must exist for customer_id lookup validation
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

WITH source_data AS (
    SELECT 
        address_id,
        customer_id,
        address_line1,
        city,
        country,
        inserted_at
    FROM {{ source('dwh_raw', 'addresses') }}
),

customer_lookup AS (
    SELECT DISTINCT customer_id
    FROM {{ ref('dim_customer') }}
),

transformed_data AS (
    SELECT 
        s.address_id,
        s.customer_id::INTEGER AS customer_id,
        TRIM(s.address_line1) AS address_line1,
        UPPER(s.city) AS city,
        s.country,
        s.inserted_at::DATE AS inserted_at
    FROM source_data s
    INNER JOIN customer_lookup c 
        ON s.customer_id::INTEGER = c.customer_id
)

SELECT * FROM transformed_data