{#
------------------------------------------------------------------------
MODEL NAME: dim_address
TARGET TABLE: bsl_ma.dwh_ma.dim_address
SOURCE TABLES: bsl_raw.dwh_raw.addresses
DESCRIPTION: Dimension table for address data with customer lookup validation and data transformations
PREREQUISITES: dim_customer table must exist for customer_id validation
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_data AS (
    SELECT
        src.address_id,
        src.customer_id,
        src.address_line1,
        src.city,
        src.country,
        src.inserted_at
    FROM {{ source('dwh_raw', 'addresses') }} src
),

customer_lookup AS (
    SELECT
        cust.customer_id
    FROM {{ ref('dim_customer') }} cust
),

validated_data AS (
    SELECT
        src.address_id,
        src.customer_id,
        src.address_line1,
        src.city,
        src.country,
        src.inserted_at
    FROM source_data src
    INNER JOIN customer_lookup cust
        ON src.customer_id = cust.customer_id
),

transformed AS (
    SELECT
        address_id,
        customer_id,
        TRIM(address_line1) AS address_line1,
        UPPER(city) AS city,
        country,
        DATE(inserted_at) AS inserted_at
    FROM validated_data
)

SELECT * FROM transformed