{#
------------------------------------------------------------------------
MODEL NAME: DIM_CATEGORY
TARGET TABLE: BSL_MA.DWH_MA.DIM_CATEGORY
SOURCE TABLES: BSL_RAW.DWH_RAW.CATEGORY
DESCRIPTION: Product category hierarchy dimension table with surrogate keys and category path building up to 2 levels
PREREQUISITES: Source table BSL_RAW.DWH_RAW.CATEGORY must be available
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

{{ config(
    materialized='table'
) }}

WITH source_data AS (
    SELECT 
        CATEGORY_ID,
        TRIM(INITCAP(CATEGORY_NAME)) AS CATEGORY_NAME,
        PARENT_CATEGORY_ID,
        COALESCE(IS_ACTIVE, TRUE) AS IS_ACTIVE
    FROM {{ source('dwh_raw', 'CATEGORY') }}
),

-- Generate surrogate keys for categories
category_with_sk AS (
    SELECT 
        {{ dbt_utils.generate_surrogate_key(['CATEGORY_ID']) }} AS CATEGORY_SK,
        CATEGORY_ID,
        CATEGORY_NAME,
        PARENT_CATEGORY_ID,
        IS_ACTIVE
    FROM source_data
),

-- Self-join to get parent category information
category_with_parent AS (
    SELECT 
        c.CATEGORY_SK,
        c.CATEGORY_ID,
        c.CATEGORY_NAME,
        c.PARENT_CATEGORY_ID,
        p.CATEGORY_SK AS PARENT_CATEGORY_SK,
        p.CATEGORY_NAME AS PARENT_CATEGORY_NAME,
        c.IS_ACTIVE
    FROM category_with_sk c
    LEFT JOIN category_with_sk p 
        ON c.PARENT_CATEGORY_ID = p.CATEGORY_ID
),

-- Build category path up to 2 levels
final AS (
    SELECT 
        CATEGORY_SK,
        CATEGORY_ID,
        CATEGORY_NAME,
        PARENT_CATEGORY_ID,
        PARENT_CATEGORY_SK,
        CASE 
            WHEN PARENT_CATEGORY_NAME IS NOT NULL 
            THEN PARENT_CATEGORY_NAME || ' > ' || CATEGORY_NAME
            ELSE CATEGORY_NAME
        END AS CATEGORY_PATH,
        IS_ACTIVE
    FROM category_with_parent
)

SELECT * FROM final