{#
------------------------------------------------------------------------
MODEL NAME: dim_address
TARGET TABLE: bsl_ma.dwh_ma.dim_address
SOURCE TABLES: bsl_raw.dwh_raw.addresses
DESCRIPTION: Dimension table for address information with customer lookup and data transformations
PREREQUISITES: dim_customer table must exist for customer_id lookup
PARAMETER: None
AUTHOUR: AI Generated by Shajahan
CREATED DATE: 2025-01-27 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_data AS (
    SELECT
        addr.address_id,
        addr.customer_id,
        addr.address_line1,
        addr.city,
        addr.country,
        addr.inserted_at
    FROM {{ source('dwh_raw', 'addresses') }} addr
),

customer_lookup AS (
    SELECT
        customer_id
    FROM {{ ref('dim_customer') }}
),

filtered_data AS (
    SELECT
        src.address_id,
        src.customer_id,
        src.address_line1,
        src.city,
        src.country,
        src.inserted_at
    FROM source_data src
    INNER JOIN customer_lookup cust
        ON src.customer_id = cust.customer_id
),

transformed AS (
    SELECT
        address_id,
        customer_id,
        TRIM(address_line1) AS address_line1,
        UPPER(city) AS city,
        country,
        DATE(inserted_at) AS inserted_at
    FROM filtered_data
)

SELECT * FROM transformed