{#
------------------------------------------------------------------------
MODEL NAME: DimCustomer
TARGET TABLE: BSL_FINAL.DWH_MA.DIMCUSTOMER
SOURCE TABLES: BSL_STAGING.DWH_STAGING.CUSTOMER, BSL_STAGING.DWH_STAGING.ADDRESS, BSL_STAGING.DWH_STAGING.CUSTOMER_ADDRESS
DESCRIPTION: Customer dimension model that stores customer profile attributes with historical tracking when customer details change. Includes customer demographics and address information through lookup joins.
PREREQUISITES: Source tables Customer, Address, and Customer_Address must be available in staging layer
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='view') }}

with customer_base as (
    select
        customer_id,
        first_name,
        last_name,
        email,
        phone,
        created_ts
    from {{ source('dwh_staging', 'customer') }}
),

address_lookup as (
    select
        a.address_id,
        a.city,
        a.state,
        a.country
    from {{ source('dwh_staging', 'address') }} a
),

customer_address_bridge as (
    select
        customer_id,
        address_id
    from {{ source('dwh_staging', 'customer_address') }}
),

final as (
    select
        cb.customer_id,
        concat(cb.first_name, ' ', cb.last_name) as full_name,
        cb.email,
        cb.phone,
        al.city,
        al.state,
        al.country,
        case 
            when cb.created_ts >= dateadd(year, -2, current_date()) 
            then true 
            else false 
        end as is_current
    from customer_base cb
    left join customer_address_bridge cab
        on cb.customer_id = cab.customer_id
    left join address_lookup al
        on cab.address_id = al.address_id
)

select * from final