{# ------------------------------------------------------------------------
MODEL NAME: DimCustomer
TARGET TABLE: bsl_final.dwh_ma.DimCustomer
SOURCE TABLES: bsl_staging.dwh_staging.Customer, bsl_staging.dwh_staging.Address, bsl_staging.dwh_staging.customer_address
DESCRIPTION: This model creates a customer dimension table that stores customer profile attributes with historical tracking when customer details change. It combines customer information with their address details and determines customer active status based on account age.
PREREQUISITES: Source tables Customer, Address, and customer_address must be available in dwh_staging schema
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2025-01-09
------------------------------------------------------------------------ #}

{{ config(
    materialized='view'
) }}

with customer_source as (
    select
        customer_id,
        first_name,
        last_name,
        email,
        phone,
        created_ts
    from {{ source('dwh_staging', 'customer') }}
),

customer_address_bridge as (
    select
        customer_id,
        address_id
    from {{ source('dwh_staging', 'customer_address') }}
),

address_source as (
    select
        address_id,
        city,
        state,
        country
    from {{ source('dwh_staging', 'address') }}
),

customer_with_address as (
    select
        c.customer_id,
        c.first_name,
        c.last_name,
        c.email,
        c.phone,
        c.created_ts,
        a.city,
        a.state,
        a.country
    from customer_source c
    left join customer_address_bridge ca
        on c.customer_id = ca.customer_id
    left join address_source a
        on ca.address_id = a.address_id
),

final as (
    select
        customer_id,
        -- Concatenate first_name and last_name as full_name
        concat(first_name, ' ', last_name) as full_name,
        email,
        phone,
        city,
        state,
        country,
        -- Customer is active only if the created_ts is less than 2 years from current_date
        case 
            when created_ts >= dateadd(year, -2, current_date()) then true
            else false
        end as is_current
    from customer_with_address
)

select * from final