{#
------------------------------------------------------------------------
MODEL NAME: DimCustomer
TARGET TABLE: BSL_FINAL.DWH_MA.DIMCUSTOMER
SOURCE TABLES: BSL_STAGING.DWH_STAGING.CUSTOMER, BSL_STAGING.DWH_STAGING.ADDRESS, BSL_STAGING.DWH_STAGING.CUSTOMER_ADDRESS
DESCRIPTION: Customer dimension model that stores customer profile attributes with historical tracking when customer details change. Includes customer demographics and address information.
PREREQUISITES: Source tables Customer, Address, and Customer_Address must be available in staging layer
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='view') }}

WITH customer_base AS (
    SELECT 
        customer_id,
        first_name,
        last_name,
        email,
        phone,
        created_ts
    FROM {{ source('dwh_staging', 'customer') }}
),

customer_address_mapping AS (
    SELECT 
        customer_id,
        address_id
    FROM {{ source('dwh_staging', 'customer_address') }}
),

address_details AS (
    SELECT 
        address_id,
        city,
        state,
        country
    FROM {{ source('dwh_staging', 'address') }}
),

customer_with_address AS (
    SELECT 
        cb.customer_id,
        cb.first_name,
        cb.last_name,
        cb.email,
        cb.phone,
        cb.created_ts,
        ad.city,
        ad.state,
        ad.country
    FROM customer_base cb
    LEFT JOIN customer_address_mapping cam 
        ON cb.customer_id = cam.customer_id
    LEFT JOIN address_details ad 
        ON cam.address_id = ad.address_id
),

final AS (
    SELECT 
        customer_id,
        CONCAT(COALESCE(first_name, ''), ' ', COALESCE(last_name, '')) AS full_name,
        email,
        phone,
        city,
        state,
        country,
        CASE 
            WHEN created_ts >= DATEADD(YEAR, -2, CURRENT_DATE()) 
            THEN TRUE 
            ELSE FALSE 
        END AS is_current
    FROM customer_with_address
)

SELECT * FROM final