{#
------------------------------------------------------------------------
MODEL NAME: DimProduct
TARGET TABLE: BSL_FINAL.DWH_MA.DIMPRODUCT
SOURCE TABLES: BSL_STAGING.DWH_STAGING.PRODUCT, BSL_STAGING.DWH_STAGING.PRODUCT_CATEGORY, BSL_STAGING.DWH_STAGING.PRODUCT_DISCOUNT, BSL_STAGING.DWH_STAGING.INVENTORY
DESCRIPTION: Dimension table that stores product master details including product name, brand, category, and pricing attributes with current unit price after discount calculations and active status based on inventory levels.
PREREQUISITES: Source tables Product, Product_Category, Product_Discount, and Inventory must be available in staging layer
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='view') }}

WITH product_base AS (
    SELECT 
        product_id,
        product_name,
        brand,
        product_category_id
    FROM {{ source('dwh_staging', 'product') }}
),

product_category AS (
    SELECT 
        category_id,
        category_name
    FROM {{ source('dwh_staging', 'product_category') }}
),

product_discount AS (
    SELECT 
        product_id,
        discount_pct,
        effective_from,
        effective_to
    FROM {{ source('dwh_staging', 'product_discount') }}
    WHERE CURRENT_DATE() BETWEEN effective_from AND effective_to
),

inventory_status AS (
    SELECT 
        product_id,
        quantity_on_hand
    FROM {{ source('dwh_staging', 'inventory') }}
),

final AS (
    SELECT 
        pb.product_id,
        pb.product_name,
        pb.brand,
        pc.category_name,
        -- Calculate current unit price after discount
        CASE 
            WHEN pd.discount_pct IS NOT NULL 
            THEN ROUND((100 - pd.discount_pct) / 100.0, 2)
            ELSE NULL 
        END AS current_unit_price,
        -- Determine active flag based on inventory quantity
        CASE 
            WHEN inv.quantity_on_hand > 0 THEN TRUE
            ELSE FALSE 
        END AS active_flag
    FROM product_base pb
    LEFT JOIN product_category pc 
        ON pb.product_category_id = pc.category_id
    LEFT JOIN product_discount pd 
        ON pb.product_id = pd.product_id
    LEFT JOIN inventory_status inv 
        ON pb.product_id = inv.product_id
)

SELECT * FROM final