{#
------------------------------------------------------------------------
MODEL NAME: DimProduct
TARGET TABLE: BSL_FINAL.DWH_MA.DIMPRODUCT
SOURCE TABLES: BSL_STAGING.DWH_STAGING.PRODUCT, BSL_STAGING.DWH_STAGING.PRODUCT_CATEGORY, BSL_STAGING.DWH_STAGING.PRODUCT_DISCOUNT, BSL_STAGING.DWH_STAGING.INVENTORY
DESCRIPTION: Stores product master details including product name, brand, category, and pricing attributes with calculated discounted prices and active status based on inventory levels.
PREREQUISITES: Source tables must be loaded and available in staging layer
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='view') }}

with product_base as (
    select
        product_id,
        product_name,
        brand
    from {{ source('dwh_staging', 'product') }}
),

product_category_lookup as (
    select
        product_category_id,
        category_name
    from {{ source('dwh_staging', 'product_category') }}
),

product_discount_lookup as (
    select
        product_id,
        discount_pct,
        effective_from,
        effective_to
    from {{ source('dwh_staging', 'product_discount') }}
    where current_date() between effective_from and effective_to
),

inventory_lookup as (
    select
        product_id,
        quantity_on_hand
    from {{ source('dwh_staging', 'inventory') }}
),

final as (
    select
        p.product_id,
        p.product_name,
        p.brand,
        pc.category_name,
        -- Calculate current unit price with discount applied
        case 
            when pd.discount_pct is not null then 
                round((100 - pd.discount_pct) / 100.0, 2)::decimal(10,2)
            else 
                1.00::decimal(10,2)
        end as current_unit_price,
        -- Determine active flag based on inventory quantity
        case 
            when inv.quantity_on_hand > 0 then true
            else false
        end as active_flag
    from product_base p
    left join product_category_lookup pc 
        on p.product_id = pc.product_category_id
    left join product_discount_lookup pd 
        on p.product_id = pd.product_id
    left join inventory_lookup inv 
        on p.product_id = inv.product_id
)

select * from final