{# ------------------------------------------------------------------------
MODEL NAME: DimProduct
TARGET TABLE: bsl_final.dwh_ma.DimProduct
SOURCE TABLES: bsl_staging.dwh_staging.Product, bsl_staging.dwh_staging.Product_Category, bsl_staging.dwh_staging.Product_Discount, bsl_staging.dwh_staging.Inventory
DESCRIPTION: This model creates a product dimension table that stores product master details including product name, brand, category, and pricing attributes. It enriches product data with category information, calculates discounted prices based on active discount periods, and determines product active status based on inventory availability.
PREREQUISITES: Source tables Product, Product_Category, Product_Discount, and Inventory must be available in dwh_staging schema.
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2025-01-09
------------------------------------------------------------------------ #}

{{ config(
    materialized='view',
    schema='dwh_ma',
    database='bsl_final'
) }}

with source_product as (
    select
        product_id,
        product_name,
        brand,
        product_category_id,
        unit_price
    from {{ source('dwh_staging', 'product') }}
),

source_product_category as (
    select
        product_category_id,
        category_name
    from {{ source('dwh_staging', 'product_category') }}
),

source_product_discount as (
    select
        product_id,
        discount_pct,
        effective_from,
        effective_to
    from {{ source('dwh_staging', 'product_discount') }}
    where current_date() between effective_from and effective_to
),

source_inventory as (
    select
        product_id,
        quantity_on_hand
    from {{ source('dwh_staging', 'inventory') }}
),

product_with_category as (
    select
        p.product_id,
        p.product_name,
        p.brand,
        pc.category_name,
        p.unit_price
    from source_product p
    left join source_product_category pc
        on p.product_category_id = pc.product_category_id
),

product_with_discount as (
    select
        pwc.product_id,
        pwc.product_name,
        pwc.brand,
        pwc.category_name,
        coalesce(
            pwc.unit_price - (pwc.unit_price * coalesce(pd.discount_pct, 0) / 100),
            pwc.unit_price
        ) as current_unit_price
    from product_with_category pwc
    left join source_product_discount pd
        on pwc.product_id = pd.product_id
),

final as (
    select
        pwd.product_id,
        pwd.product_name,
        pwd.brand,
        pwd.category_name,
        pwd.current_unit_price,
        case
            when coalesce(inv.quantity_on_hand, 0) > 0 then true
            else false
        end as active_flag
    from product_with_discount pwd
    left join source_inventory inv
        on pwd.product_id = inv.product_id
)

select
    product_id,
    product_name,
    brand,
    category_name,
    current_unit_price,
    active_flag
from final