{#
------------------------------------------------------------------------
MODEL NAME: fact_inventory
TARGET TABLE: bsl_ma.dwh_ma.fact_inventory
SOURCE TABLES: bsl_raw.dwh_raw.inventory
DESCRIPTION: Inventory latest snapshot fact table with product and supplier lookups, data quality checks, and latest record flagging
PREREQUISITES: dim_product and dim_supplier tables must exist
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table',
    schema = 'dwh_ma',
    alias = 'fact_inventory'
) }}

WITH source_data AS (
    SELECT
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated
    FROM {{ source('dwh_raw', 'inventory') }}
),

-- Get latest record flag per product_id and supplier_id
latest_records AS (
    SELECT
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated,
        ROW_NUMBER() OVER (
            PARTITION BY product_id, supplier_id 
            ORDER BY last_updated DESC
        ) = 1 AS is_latest
    FROM source_data
),

-- Apply product lookup with fallback to unknown
product_lookup AS (
    SELECT
        lr.*,
        COALESCE(dp.product_id, '0') AS final_product_id
    FROM latest_records lr
    LEFT JOIN {{ ref('dim_product') }} dp 
        ON lr.product_id = dp.product_id
),

-- Apply supplier lookup with fallback to unknown
supplier_lookup AS (
    SELECT
        pl.*,
        COALESCE(ds.supplier_id, '0') AS final_supplier_id
    FROM product_lookup pl
    LEFT JOIN {{ ref('dim_supplier') }} ds 
        ON pl.supplier_id = ds.supplier_id
),

transformed AS (
    SELECT
        final_product_id AS product_id,
        final_supplier_id AS supplier_id,
        -- Set negative stock quantities to null
        CASE 
            WHEN stock_qty < 0 THEN NULL 
            ELSE stock_qty 
        END AS stock_qty,
        -- Uppercase warehouse location
        UPPER(warehouse_location) AS warehouse_location,
        -- Convert timestamp to date
        last_updated::DATE AS snapshot_date,
        is_latest
    FROM supplier_lookup
)

SELECT * FROM transformed