{#
------------------------------------------------------------------------
MODEL NAME: fact_payment
TARGET TABLE: bsl_ma.dwh_ma.fact_payment
SOURCE TABLES: bsl_raw.dwh_raw.payments, bsl_ma.dwh_ma.fact_order
DESCRIPTION: This model transforms raw payment data into a structured fact table with proper data types, validation, and enrichment including order lookup and payment application status
PREREQUISITES: fact_order table must exist and be populated
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='payment_id',
    on_schema_change='fail'
) }}

with source_payments as (
    select * from {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
    where payment_date::date > (select coalesce(max(payment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

fact_order as (
    select 
        order_id,
        total_amount
    from {{ ref('fact_order') }}
),

payment_transformations as (
    select
        sp.payment_id,
        fo.order_id::integer as order_id,
        sp.payment_date::date as payment_date,
        case 
            when upper(sp.payment_method) in ('CARD', 'UPI', 'COD', 'NETBANKING') 
            then upper(sp.payment_method)
            else 'CARD'
        end as payment_method,
        case 
            when sp.amount < 0 then null
            else sp.amount
        end as amount,
        fo.total_amount as order_total_amount
    from source_payments sp
    inner join fact_order fo on sp.order_id = fo.order_id
),

payment_aggregations as (
    select
        order_id,
        sum(coalesce(amount, 0)) as total_payments
    from payment_transformations
    group by order_id
),

final as (
    select
        pt.payment_id,
        pt.order_id,
        pt.payment_date,
        pt.payment_method,
        pt.amount,
        case 
            when pt.order_total_amount is null then false
            when pa.total_payments >= pt.order_total_amount then true
            else false
        end as is_fully_applied
    from payment_transformations pt
    left join payment_aggregations pa on pt.order_id = pa.order_id
)

select * from final