{#
------------------------------------------------------------------------
MODEL NAME    : fact_payment
TARGET TABLE  : bsl_ma.dwh_ma.fact_payment
SOURCE TABLES : bsl_raw.dwh_raw.payments, bsl_raw.dwh_raw.orders
DESCRIPTION   : Fact table for payment transactions with order validation
                and payment method standardization. Includes derived
                is_fully_applied flag based on payment vs order totals.
PREREQUISITES : fact_order model must exist for order validation
PARAMETER     : None
AUTHOR        : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='payment_id'
) }}

WITH payments_source AS (
    SELECT
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount
    FROM {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
        WHERE payment_date::date > (select coalesce(max(payment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

orders_source AS (
    SELECT
        order_id,
        total_amount
    FROM {{ source('dwh_raw', 'orders') }}
),

fact_order_ref AS (
    SELECT
        order_id
    FROM {{ ref('fact_order') }}
),

payment_aggregates AS (
    SELECT
        ps.order_id,
        SUM(ps.amount) AS total_payments
    FROM payments_source ps
    GROUP BY ps.order_id
),

transformed AS (
    SELECT
        ps.payment_id,
        ps.order_id,
        ps.payment_date::date AS payment_date,
        CASE 
            WHEN UPPER(ps.payment_method) IN ('CARD', 'UPI', 'COD', 'NETBANKING') 
            THEN UPPER(ps.payment_method)
            ELSE 'CARD'
        END AS payment_method,
        CASE 
            WHEN ps.amount < 0 THEN NULL
            ELSE ps.amount
        END AS amount,
        CASE 
            WHEN os.total_amount IS NULL THEN FALSE
            WHEN pa.total_payments >= os.total_amount THEN TRUE
            ELSE FALSE
        END AS is_fully_applied
    FROM payments_source ps
    INNER JOIN fact_order_ref fo ON ps.order_id = fo.order_id
    LEFT JOIN orders_source os ON ps.order_id = os.order_id
    LEFT JOIN payment_aggregates pa ON ps.order_id = pa.order_id
)

SELECT * FROM transformed