{#
------------------------------------------------------------------------
MODEL NAME: FACT_SHIPMENT
TARGET TABLE: BSL_MA.DWH_MA.FACT_SHIPMENT
SOURCE TABLES: BSL_RAW.DWH_RAW.SHIPMENTS
DESCRIPTION: Shipment fact table that transforms raw shipment data into a dimensional model with surrogate keys, date conversions, and calculated metrics like days to ship
PREREQUISITES: FACT_ORDER table must exist for ORDER_SK lookup
PARAMETER: Incremental load based on SHIPPED_DATE
AUTHOUR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='SHIPMENT_ID'
) }}

with shipments_raw as (
    select *
    from {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        where SHIPPED_DATE::date > (select coalesce(max(SHIPPED_DATE), '1900-01-01') from {{ this }})
    {% endif %}
),

fact_order as (
    select 
        ORDER_ID,
        ORDER_SK,
        ORDER_DATE
    from {{ ref('FACT_ORDER') }}
),

transformed as (
    select
        -- Generate surrogate key from SHIPMENT_ID
        {{ dbt_utils.generate_surrogate_key(['s.SHIPMENT_ID']) }} as SHIPMENT_SK,
        
        -- Direct mapping of SHIPMENT_ID
        s.SHIPMENT_ID,
        
        -- Lookup ORDER_SK from FACT_ORDER using ORDER_ID
        o.ORDER_SK,
        
        -- Convert timestamp to date
        s.SHIPPED_DATE::date as SHIPPED_DATE,
        
        -- Calculate days to ship with floor at 0 for negative values
        greatest(0, datediff('day', o.ORDER_DATE, s.SHIPPED_DATE)) as DAYS_TO_SHIP,
        
        -- Uppercase carrier
        upper(s.CARRIER) as CARRIER,
        
        -- Direct mapping of tracking number
        s.TRACKING_NUMBER
        
    from shipments_raw s
    left join fact_order o
        on s.ORDER_ID = o.ORDER_ID
    -- Skip records where order is missing
    where o.ORDER_SK is not null
)

select * from transformed