{# ------------------------------------------------------------------------
MODEL NAME: FactReturns
TARGET TABLE: bsl_final.dwh_ma.FactReturns
SOURCE TABLES: bsl_staging.dwh_staging.Returns, bsl_staging.dwh_staging.Order_Line
DESCRIPTION: Captures product return events with return date, return reason, and associated order line. This model transforms staging return data and enriches it with product information from order lines.
PREREQUISITES: Source tables bsl_staging.dwh_staging.Returns and bsl_staging.dwh_staging.Order_Line must be available and populated.
PARAMETER: Incremental model filtered by return_date > max(return_date)
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2025-01-09
------------------------------------------------------------------------ #}

{{ config(
    materialized='incremental',
    unique_key='order_line_id',
    schema='dwh_ma',
    database='bsl_final'
) }}

with source_returns as (
    select
        return_date,
        order_line_id,
        return_reason
    from {{ source('dwh_staging', 'returns') }}
    {% if is_incremental() %}
    where return_date > (select max(return_date) from {{ this }})
    {% endif %}
),

source_order_line as (
    select
        order_line_id,
        product_id
    from {{ source('dwh_staging', 'order_line') }}
),

final as (
    select
        sr.return_date,
        sr.order_line_id,
        sol.product_id,
        sr.return_reason
    from source_returns sr
    left join source_order_line sol
        on sr.order_line_id = sol.order_line_id
)

select * from final