{#
------------------------------------------------------------------------
MODEL NAME: fact_order
TARGET TABLE: bsl_ma.dwh_ma.fact_order
SOURCE TABLES: bsl_raw.dwh_raw.orders
DESCRIPTION: Fact table for orders with customer lookup and data transformations
PREREQUISITES: dim_customer table must exist for customer_id lookup
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

select 
    o.order_id,
    dc.customer_id::integer as customer_id,
    o.order_date::date as order_date,
    case 
        when upper(o.status) in ('PENDING', 'PAID', 'CANCELLED', 'SHIPPED') 
        then upper(o.status)
        else 'PENDING'
    end as order_status,
    case 
        when o.total_amount < 0 then null
        else o.total_amount::number(10,2)
    end as total_amount
from {{ source('dwh_raw', 'orders') }} o
inner join {{ ref('dim_customer') }} dc 
    on o.customer_id = dc.customer_id

{% if is_incremental() %}
where o.order_date::date > (select coalesce(max(order_date), '1900-01-01') from {{ this }})
{% endif %}