{#
------------------------------------------------------------------------
MODEL NAME: FactSales
TARGET TABLE: BSL_FINAL.DWH_MA.FACTSALES
SOURCE TABLES: BSL_STAGING.DWH_STAGING.ORDER_HEADER, BSL_STAGING.DWH_STAGING.PRODUCT_DISCOUNT
DESCRIPTION: Line-level sales fact capturing quantities sold and financial metrics per product and order line with calculated gross amount, discount amount, and net amount.
PREREQUISITES: Source tables ORDER_HEADER and PRODUCT_DISCOUNT must be available in staging layer
PARAMETER: Incremental model based on order_date with condition order_date > max(order_date)
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_line_id'
) }}

with staging_data as (
    select
        order_date,
        customer_id,
        product_id,
        order_id,
        order_line_id,
        quantity,
        unit_price
    from {{ source('dwh_staging', 'order_header') }}
    {% if is_incremental() %}
        where order_date > (select max(order_date) from {{ this }})
    {% endif %}
),

product_discount_data as (
    select
        product_id,
        discount_pct
    from {{ source('dwh_staging', 'product_discount') }}
),

final_calculations as (
    select
        sd.order_date,
        sd.customer_id,
        sd.product_id,
        sd.order_id,
        sd.order_line_id,
        sd.quantity as quantity_sold,
        -- Calculate gross amount: quantity * unit_price
        (sd.quantity * sd.unit_price) as gross_amount,
        -- Calculate discount amount: unit_price * discount_pct
        (sd.unit_price * coalesce(pdd.discount_pct, 0)) as discount_amount,
        -- Calculate net amount: (quantity * unit_price) - (unit_price * discount_pct)
        ((sd.quantity * sd.unit_price) - (sd.unit_price * coalesce(pdd.discount_pct, 0))) as net_amount
    from staging_data sd
    left join product_discount_data pdd
        on sd.product_id = pdd.product_id
)

select
    order_date,
    customer_id,
    product_id,
    order_id,
    order_line_id,
    quantity_sold,
    gross_amount,
    discount_amount,
    net_amount
from final_calculations