{#
------------------------------------------------------------------------
MODEL NAME: fact_shipment
TARGET TABLE: bsl_ma.dwh_ma.fact_shipment
SOURCE TABLES: bsl_raw.dwh_raw.shipments, bsl_ma.dwh_ma.fact_order
DESCRIPTION: This model creates a fact table for shipments by transforming raw shipment data and enriching it with order information. It calculates days to ship and applies data quality rules.
PREREQUISITES: fact_order model must exist and be populated
PARAMETER: Incremental model based on shipment_date
AUTHOUR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='shipment_id'
) }}

with source_shipments as (
    select 
        shipment_id,
        order_id,
        shipped_date,
        carrier,
        tracking_number
    from {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        where shipped_date::date > (select coalesce(max(shipped_date), '1900-01-01') from {{ this }})
    {% endif %}
),

fact_order_lookup as (
    select 
        order_id,
        order_date
    from {{ ref('fact_order') }}
),

transformed_shipments as (
    select 
        s.shipment_id,
        s.order_id,
        s.shipped_date::date as shipped_date,
        upper(s.carrier) as carrier,
        s.tracking_number,
        greatest(0, datediff('day', o.order_date::date, s.shipped_date::date)) as days_to_ship
    from source_shipments s
    inner join fact_order_lookup o
        on s.order_id = o.order_id
)

select 
    shipment_id,
    order_id,
    shipped_date,
    carrier,
    tracking_number,
    days_to_ship
from transformed_shipments