{#
------------------------------------------------------------------------
MODEL NAME: FACT_ORDER
TARGET TABLE: BSL_MA.DWH_MA.FACT_ORDER
SOURCE TABLES: BSL_RAW.DWH_RAW.ORDERS, BSL_MA.DWH_MA.DIM_CUSTOMER
DESCRIPTION: Order fact table at order level that transforms raw order data into a structured fact table with surrogate keys and data quality validations
PREREQUISITES: DIM_CUSTOMER table must exist and be populated
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='ORDER_ID'
) }}

WITH source_data AS (
    SELECT 
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_DATE,
        STATUS,
        TOTAL_AMOUNT
    FROM {{ source('raw', 'orders') }}
    WHERE ORDER_DATE IS NOT NULL
    {% if is_incremental() %}
        AND ORDER_DATE::date > (SELECT COALESCE(MAX(ORDER_DATE), '1900-01-01') FROM {{ this }})
    {% endif %}
),

customer_lookup AS (
    SELECT 
        CUSTOMER_ID,
        CUSTOMER_SK
    FROM {{ ref('dim_customer') }}
),

transformed_data AS (
    SELECT 
        -- Generate surrogate key from ORDER_ID
        {{ dbt_utils.generate_surrogate_key(['s.ORDER_ID']) }} AS ORDER_SK,
        
        -- Direct mapping of ORDER_ID
        s.ORDER_ID,
        
        -- Lookup CUSTOMER_SK from DIM_CUSTOMER
        c.CUSTOMER_SK,
        
        -- Convert timestamp to date
        s.ORDER_DATE::DATE AS ORDER_DATE,
        
        -- Normalize status to UPPER and map to accepted values
        CASE 
            WHEN UPPER(s.STATUS) IN ('PENDING', 'PAID', 'CANCELLED', 'SHIPPED') 
            THEN UPPER(s.STATUS)
            ELSE 'PENDING'
        END AS ORDER_STATUS,
        
        -- Handle negative amounts by setting to null
        CASE 
            WHEN s.TOTAL_AMOUNT < 0 THEN NULL
            ELSE s.TOTAL_AMOUNT
        END AS TOTAL_AMOUNT
        
    FROM source_data s
    INNER JOIN customer_lookup c
        ON s.CUSTOMER_ID = c.CUSTOMER_ID
)

SELECT 
    ORDER_SK,
    ORDER_ID,
    CUSTOMER_SK,
    ORDER_DATE,
    ORDER_STATUS,
    TOTAL_AMOUNT
FROM transformed_data