{#
------------------------------------------------------------------------
MODEL NAME    : fact_inventory
TARGET TABLE  : bsl_ma.dwh_ma.fact_inventory
SOURCE TABLES : bsl_raw.dwh_raw.inventory
DESCRIPTION   : Inventory latest snapshot fact table with product and 
                supplier lookups, stock quantities, warehouse locations
                and snapshot dates with latest record flags
PREREQUISITES : dim_product and dim_supplier tables must exist
PARAMETER     : None
AUTHOUR       : AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'table'
) }}

WITH source_data AS (
    SELECT
        inv.product_id,
        inv.supplier_id,
        inv.stock_qty,
        inv.warehouse_location,
        inv.last_updated
    FROM {{ source('dwh_raw', 'inventory') }} inv
),

product_lookup AS (
    SELECT
        product_id
    FROM {{ ref('dim_product') }}
),

supplier_lookup AS (
    SELECT
        supplier_id  
    FROM {{ ref('dim_supplier') }}
),

latest_records AS (
    SELECT
        src.product_id,
        src.supplier_id,
        src.stock_qty,
        src.warehouse_location,
        src.last_updated,
        ROW_NUMBER() OVER (
            PARTITION BY src.product_id, src.supplier_id 
            ORDER BY src.last_updated DESC
        ) AS rn
    FROM source_data src
),

transformed AS (
    SELECT
        -- Product ID lookup with unknown handling
        COALESCE(pl.product_id, lr.product_id, '0') AS product_id,
        
        -- Supplier ID lookup with unknown handling  
        COALESCE(sl.supplier_id, lr.supplier_id, '0') AS supplier_id,
        
        -- Stock quantity with negative value handling
        CASE 
            WHEN lr.stock_qty < 0 THEN NULL
            ELSE lr.stock_qty
        END AS stock_qty,
        
        -- Uppercase warehouse location
        UPPER(lr.warehouse_location) AS warehouse_location,
        
        -- Convert timestamp to date
        DATE(lr.last_updated) AS snapshot_date,
        
        -- Flag latest record per product_id + supplier_id
        CASE WHEN lr.rn = 1 THEN TRUE ELSE FALSE END AS is_latest
        
    FROM latest_records lr
    LEFT JOIN product_lookup pl 
        ON lr.product_id = pl.product_id
    LEFT JOIN supplier_lookup sl 
        ON lr.supplier_id = sl.supplier_id
)

SELECT * FROM transformed