{#
------------------------------------------------------------------------
MODEL NAME: FACT_ORDER
TARGET TABLE: BSL_MA.DWH_MA.FACT_ORDER
SOURCE TABLES: BSL_RAW.DWH_RAW.ORDER_ID
DESCRIPTION: Order fact table at order level with transformed and cleansed order data
PREREQUISITES: DIM_CUSTOMER table must exist for customer lookup
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='ORDER_ID'
) }}

with source_data as (
    select *
    from {{ source('dwh_raw', 'ORDER_ID') }}
    {% if is_incremental() %}
        where ORDER_DATE::date > (select coalesce(max(ORDER_DATE), '1900-01-01') from {{ this }})
    {% endif %}
),

customer_lookup as (
    select 
        CUSTOMER_ID,
        CUSTOMER_SK
    from {{ ref('DIM_CUSTOMER') }}
),

transformed as (
    select
        -- Generate surrogate key from ORDER_ID
        {{ dbt_utils.generate_surrogate_key(['s.ORDER_ID']) }} as ORDER_SK,
        
        -- Direct mapping of ORDER_ID
        s.ORDER_ID,
        
        -- Lookup CUSTOMER_SK from DIM_CUSTOMER
        c.CUSTOMER_SK,
        
        -- Convert timestamp to date
        s.ORDER_DATE::date as ORDER_DATE,
        
        -- Normalize status to UPPER and map to accepted values
        case 
            when upper(s.STATUS) in ('PENDING', 'PAID', 'CANCELLED', 'SHIPPED') 
            then upper(s.STATUS)
            else 'PENDING'
        end as ORDER_STATUS,
        
        -- Handle negative amounts by setting to null
        case 
            when s.TOTAL_AMOUNT < 0 then null
            else s.TOTAL_AMOUNT
        end as TOTAL_AMOUNT
        
    from source_data s
    left join customer_lookup c on s.CUSTOMER_ID = c.CUSTOMER_ID
    where s.ORDER_DATE is not null  -- Do not upsert rows where ORDER_DATE is null
      and c.CUSTOMER_SK is not null  -- Skip order rows with no matching customer
)

select * from transformed