{#
------------------------------------------------------------------------
MODEL NAME: fact_order
TARGET TABLE: bsl_ma.dwh_ma.fact_order
SOURCE TABLES: bsl_raw.dwh_raw.orders
DESCRIPTION: This model transforms raw order data into a fact table with proper data type conversions, status normalization, and customer validation through dimension lookup.
PREREQUISITES: dim_customer table must exist for customer lookup validation
PARAMETER: Incremental model based on order_date with lookback to maximum existing date
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

with source_data as (
    select 
        order_id,
        customer_id,
        order_date,
        status,
        total_amount
    from {{ source('dwh_raw', 'orders') }}
    {% if is_incremental() %}
        where order_date::date > (select coalesce(max(order_date), '1900-01-01') from {{ this }})
    {% endif %}
),

customer_lookup as (
    select 
        customer_id
    from {{ ref('dim_customer') }}
),

validated_orders as (
    select 
        s.order_id,
        s.customer_id,
        s.order_date,
        s.status,
        s.total_amount
    from source_data s
    inner join customer_lookup c
        on s.customer_id = c.customer_id
),

transformed_orders as (
    select 
        order_id,
        customer_id,
        order_date::date as order_date,
        case 
            when upper(status) in ('PENDING', 'CANCELLED', 'SHIPPED', 'DELIVERED') 
            then upper(status)
            else 'PENDING'
        end as order_status,
        case 
            when total_amount < 0 then null
            else total_amount::number(10,2)
        end as total_amount
    from validated_orders
)

select * from transformed_orders