{#
------------------------------------------------------------------------
MODEL NAME: FactReturns
TARGET TABLE: BSL_FINAL.DWH_MA.FACTRETURNS
SOURCE TABLES: BSL_STAGING.DWH_STAGING.RETURNS, BSL_STAGING.DWH_STAGING.ORDER_LINE
DESCRIPTION: This model captures product return events with return date, return reason, and associated order line information. It performs a lookup to get product_id from Order_Line table based on order_line_id.
PREREQUISITES: Source tables BSL_STAGING.DWH_STAGING.RETURNS and BSL_STAGING.DWH_STAGING.ORDER_LINE must be available
PARAMETER: Incremental model with condition return_date > max(return_date)
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_line_id'
) }}

with returns_source as (
    select
        return_date,
        order_line_id,
        return_reason
    from {{ source('dwh_staging', 'returns') }}
    {% if is_incremental() %}
        where return_date > (select max(return_date) from {{ this }})
    {% endif %}
),

order_line_lookup as (
    select
        order_line_id,
        product_id
    from {{ source('dwh_staging', 'order_line') }}
),

final as (
    select
        r.return_date,
        r.order_line_id,
        ol.product_id,
        r.return_reason
    from returns_source r
    left join order_line_lookup ol
        on r.order_line_id = ol.order_line_id
)

select * from final