{#
------------------------------------------------------------------------
MODEL NAME    : fact_payment
TARGET TABLE  : bsl_ma.dwh_ma.fact_payment
SOURCE TABLES : bsl_raw.dwh_raw.payments, bsl_raw.dwh_raw.orders
DESCRIPTION   : This model transforms raw payment data into a fact table
                with payment details, order relationships, and payment
                status indicators for analytical reporting
PREREQUISITES : fact_order table must exist for order lookups
PARAMETER     : Incremental model based on payment_date
AUTHOR        : AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='payment_id'
) }}

WITH payments_source AS (
    SELECT
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount
    FROM {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
        WHERE payment_date::date > (select coalesce(max(payment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

orders_source AS (
    SELECT
        order_id,
        total_amount
    FROM {{ source('dwh_raw', 'orders') }}
),

fact_order_data AS (
    SELECT
        order_id,
        total_amount
    FROM {{ ref('fact_order') }}
),

payment_aggregates AS (
    SELECT
        payments.order_id,
        SUM(payments.amount) AS total_payments
    FROM payments_source payments
    GROUP BY payments.order_id
),

transformed AS (
    SELECT
        payments.payment_id,
        payments.order_id,
        payments.payment_date::date AS payment_date,
        CASE 
            WHEN UPPER(payments.payment_method) IN ('CARD', 'UPI', 'COD', 'NETBANKING') 
            THEN UPPER(payments.payment_method)
            ELSE 'CARD'
        END AS payment_method,
        CASE 
            WHEN payments.amount < 0 THEN NULL
            ELSE payments.amount
        END AS amount,
        CASE 
            WHEN fact_orders.total_amount IS NULL THEN FALSE
            WHEN payment_agg.total_payments >= fact_orders.total_amount THEN TRUE
            ELSE FALSE
        END AS is_fully_applied
    FROM payments_source payments
    INNER JOIN fact_order_data fact_orders
        ON payments.order_id = fact_orders.order_id
    LEFT JOIN payment_aggregates payment_agg
        ON payments.order_id = payment_agg.order_id
)

SELECT * FROM transformed