{#
------------------------------------------------------------------------
MODEL NAME: fact_inventory
TARGET TABLE: bsl_ma.dwh_ma.fact_inventory
SOURCE TABLES: bsl_raw.dwh_raw.inventory
DESCRIPTION: Inventory latest snapshot fact table that transforms raw inventory data with proper lookups and data quality checks
PREREQUISITES: dim_product and dim_supplier tables must exist for proper lookups
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

with source_inventory as (
    select 
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated
    from {{ source('dwh_raw', 'inventory') }}
),

product_lookup as (
    select 
        product_id
    from {{ ref('dim_product') }}
),

supplier_lookup as (
    select 
        supplier_id  
    from {{ ref('dim_supplier') }}
),

transformed_inventory as (
    select
        -- Product ID lookup with unknown handling
        coalesce(p.product_id, '0') as product_id,
        
        -- Supplier ID lookup with unknown handling  
        coalesce(s.supplier_id, '0') as supplier_id,
        
        -- Stock quantity with negative value handling
        case 
            when si.stock_qty < 0 then null
            else si.stock_qty
        end as stock_qty,
        
        -- Warehouse location uppercase transformation
        upper(si.warehouse_location) as warehouse_location,
        
        -- Convert timestamp to date
        si.last_updated::date as snapshot_date,
        
        -- Flag for latest record per composite key
        case 
            when si.last_updated = max(si.last_updated) over (
                partition by coalesce(p.product_id, '0'), coalesce(s.supplier_id, '0')
            ) then true
            else false
        end as is_latest,
        
        si.last_updated
        
    from source_inventory si
    left join product_lookup p 
        on si.product_id = p.product_id
    left join supplier_lookup s 
        on si.supplier_id = s.supplier_id
),

final as (
    select
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        snapshot_date,
        is_latest
    from transformed_inventory
)

select * from final