{#
------------------------------------------------------------------------
MODEL NAME: fact_order_item
TARGET TABLE: BSL_MA.DWH_MA.FACT_ORDER_ITEM
SOURCE TABLES: BSL_RAW.DWH_RAW.ORDER_ITEMS
DESCRIPTION: Fact table for order items with calculated extended amounts, discount allocations, and net amounts. Includes lookups to order and product dimensions.
PREREQUISITES: fact_order and dim_product tables must exist and be populated
PARAMETER: Incremental model with custom incremental condition
AUTHOR: AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_item_id'
) }}

with source_data as (
    select *
    from {{ source('dwh_raw', 'order_items') }}
    {% if is_incremental() %}
    where exists (select 1 where true) and {{ is_incremental() }}
    {% endif %}
),

order_lookup as (
    select 
        order_id::integer as order_id_int,
        order_id as order_id_varchar
    from {{ ref('fact_order') }}
),

product_lookup as (
    select 
        product_id::integer as product_id_int,
        product_id as product_id_varchar,
        coalesce(product_sk, 0) as product_sk
    from {{ ref('dim_product') }}
),

transformed as (
    select
        s.order_item_id,
        
        -- Order ID lookup with skip logic for missing orders
        o.order_id_int as order_id,
        
        -- Product ID lookup with unknown handling
        coalesce(p.product_id_int, 0) as product_id,
        coalesce(p.product_sk, 0) as product_sk,
        
        -- Direct mappings with data type handling
        round(s.quantity) as quantity,
        s.unit_price::number(10,2) as unit_price,
        
        -- Calculated extended amount
        (round(s.quantity) * coalesce(s.unit_price::number(10,2), 0))::number(12,2) as extended_amount,
        
        -- Discount amount allocation (set to 0 for now as no discount context)
        0::number(12,2) as discount_amount,
        
        -- Net amount calculation ensuring non-negative
        greatest(
            0,
            (round(s.quantity) * coalesce(s.unit_price::number(10,2), 0))::number(12,2) - 0::number(12,2)
        )::number(12,2) as net_amount
        
    from source_data s
    inner join order_lookup o 
        on s.order_id = o.order_id_varchar
    left join product_lookup p 
        on s.product_id = p.product_id_varchar
    
    -- Skip items if order_id missing in fact_order
    where o.order_id_int is not null
)

select * from transformed