{#
------------------------------------------------------------------------
MODEL NAME: FactInventorySnapshot
TARGET TABLE: BSL_FINAL.DWH_MA.FACTINVENTORYSNAPSHOT
SOURCE TABLES: BSL_STAGING.DWH_STAGING.INVENTORY
DESCRIPTION: Daily snapshot of inventory quantities for each product in each warehouse location.
PREREQUISITES: Source table BSL_STAGING.DWH_STAGING.INVENTORY must be available and populated
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

WITH inventory_snapshot AS (
    SELECT
        CURRENT_DATE() AS snapshot_date,
        product_id,
        warehouse_id,
        quantity_on_hand
    FROM {{ source('dwh_staging', 'inventory') }}
)

SELECT
    snapshot_date,
    product_id,
    warehouse_id,
    quantity_on_hand
FROM inventory_snapshot