{#
------------------------------------------------------------------------
MODEL NAME: fact_order_item
TARGET TABLE: bsl_ma.dwh_ma.fact_order_item
SOURCE TABLES: bsl_raw.dwh_raw.order_items, bsl_raw.dwh_raw.orders
DESCRIPTION: Fact table for order items with calculated extended amounts, discount allocations, and net amounts. Includes lookups to validate order and product references.
PREREQUISITES: fact_order and dim_product models must exist for lookup validations
PARAMETER: Incremental model with conditional loading based on existence checks
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    schema = 'dwh_ma',
    alias = 'fact_order_item'
) }}

WITH source_order_items AS (
    SELECT
        order_item_id,
        order_id,
        product_id,
        quantity,
        unit_price
    FROM {{ source('dwh_raw', 'order_items') }}
    {% if is_incremental() %}
    WHERE exists (select 1 where true) and {{ is_incremental() }}
    {% endif %}
),

source_orders AS (
    SELECT
        order_id
    FROM {{ source('dwh_raw', 'orders') }}
),

order_validation AS (
    SELECT
        oi.order_item_id,
        oi.order_id,
        oi.product_id,
        oi.quantity,
        oi.unit_price
    FROM source_order_items oi
    INNER JOIN {{ ref('fact_order') }} fo ON oi.order_id = fo.order_id
),

product_validation AS (
    SELECT
        ov.order_item_id,
        ov.order_id,
        COALESCE(dp.product_id, '0') AS product_id,
        ov.quantity,
        ov.unit_price
    FROM order_validation ov
    LEFT JOIN {{ ref('dim_product') }} dp ON ov.product_id = dp.product_id
),

transformed AS (
    SELECT
        order_item_id,
        order_id,
        product_id,
        ROUND(quantity) AS quantity, -- Ensure integer semantics
        unit_price,
        ROUND(quantity, 0) * COALESCE(unit_price, 0) AS extended_amount, -- Compute quantity * unit_price, treat null unit_price as 0
        0.00 AS discount_amount, -- Set 0 if no discount context
        GREATEST(0, ROUND(quantity, 0) * COALESCE(unit_price, 0) - 0.00) AS net_amount -- Compute extended_amount - discount_amount, floor at 0
    FROM product_validation
)

SELECT * FROM transformed