{#
------------------------------------------------------------------------
MODEL NAME: fact_order_item
TARGET TABLE: BSL_MA.DWH_MA.FACT_ORDER_ITEM
SOURCE TABLES: BSL_RAW.DWH_RAW.ORDER_ITEMS
DESCRIPTION: This model transforms raw order item data into a fact table with calculated extended amounts, discount allocations, and net amounts. It performs lookups against order and product dimensions and applies business rules for data quality.
PREREQUISITES: fact_order and dim_product tables must exist and be populated
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_item_id'
) }}

with source_data as (
    select 
        order_id,
        product_id,
        quantity,
        unit_price,
        order_item_id
    from {{ source('dwh_raw', 'order_items') }}
    {% if is_incremental() %}
    where exists (select 1 where true) and {{ is_incremental() }}
    {% endif %}
),

order_lookup as (
    select distinct order_id
    from {{ ref('fact_order') }}
),

product_lookup as (
    select distinct product_id
    from {{ ref('dim_product') }}
),

transformed_data as (
    select 
        -- Convert order_id to integer and validate against fact_order
        cast(s.order_id as integer) as order_id,
        
        -- Handle product_id lookup with default fallback
        case 
            when p.product_id is not null then s.product_id
            else '0'
        end as product_id,
        
        -- Ensure integer semantics for quantity
        round(s.quantity, 0) as quantity,
        
        -- Direct mapping for unit_price
        s.unit_price,
        
        -- Calculate extended_amount (quantity * unit_price)
        round(
            s.quantity * coalesce(s.unit_price, 0), 
            2
        ) as extended_amount,
        
        -- Set discount_amount to 0 (no discount context available)
        0.00 as discount_amount,
        
        s.order_item_id
        
    from source_data s
    inner join order_lookup o on cast(s.order_id as integer) = o.order_id
    left join product_lookup p on s.product_id = p.product_id
),

final as (
    select 
        order_id,
        product_id,
        quantity,
        cast(unit_price as number(10,2)) as unit_price,
        cast(extended_amount as number(12,2)) as extended_amount,
        cast(discount_amount as number(12,2)) as discount_amount,
        -- Calculate net_amount ensuring non-negative result
        cast(
            greatest(0, extended_amount - discount_amount) as number(12,2)
        ) as net_amount,
        order_item_id
    from transformed_data
)

select * from final