{#
------------------------------------------------------------------------
MODEL NAME: fact_order
TARGET TABLE: bsl_ma.dwh_ma.fact_order
SOURCE TABLES: bsl_raw.dwh_raw.orders
DESCRIPTION: This model transforms raw order data into a fact table for analytical purposes. It includes order details, customer information, order status normalization, and total amount validation.
PREREQUISITES: dim_customer table must exist for customer lookup validation
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id',
    incremental_strategy='merge'
) }}

WITH source_data AS (
    SELECT
        src.order_id,
        src.customer_id,
        src.order_date,
        src.status,
        src.total_amount
    FROM {{ source('dwh_raw', 'orders') }} src
    {% if is_incremental() %}
        WHERE src.order_date::date > (select coalesce(max(order_date), '1900-01-01') from {{ this }})
    {% endif %}
),

customer_lookup AS (
    SELECT
        customer_id
    FROM {{ ref('dim_customer') }}
),

transformed AS (
    SELECT
        src.order_id,
        src.customer_id,
        src.order_date::date AS order_date,
        CASE 
            WHEN UPPER(src.status) IN ('PENDING', 'CANCELLED', 'SHIPPED', 'DELIVERED') 
            THEN UPPER(src.status)
            ELSE 'PENDING'
        END AS order_status,
        CASE 
            WHEN src.total_amount < 0 THEN NULL
            ELSE src.total_amount
        END AS total_amount
    FROM source_data src
    INNER JOIN customer_lookup cl
        ON src.customer_id = cl.customer_id
)

SELECT * FROM transformed