{# ------------------------------------------------------------------------
MODEL NAME: FactInventorySnapshot
TARGET TABLE: bsl_final.dwh_ma.FactInventorySnapshot
SOURCE TABLES: bsl_staging.dwh_staging.Inventory
DESCRIPTION: Daily snapshot of inventory quantities for each product in each warehouse location.
PREREQUISITES: Source table bsl_staging.dwh_staging.Inventory must be available and populated.
PARAMETER: None
AUTHOUR: AI Generated by Shajahan
CREATED DATE: 2024-01-09 IST
------------------------------------------------------------------------ #}

{{ config(
    materialized='view',
    schema='dwh_ma',
    database='bsl_final'
) }}

with source_inventory as (
    select
        product_id,
        warehouse_id,
        quantity_on_hand
    from {{ source('dwh_staging', 'inventory') }}
),

final as (
    select
        current_date() as snapshot_date,
        product_id,
        warehouse_id,
        quantity_on_hand
    from source_inventory
)

select
    snapshot_date,
    product_id,
    warehouse_id,
    quantity_on_hand
from final