{#
------------------------------------------------------------------------
MODEL NAME: FactShipment
TARGET TABLE: BSL_FINAL.DWH_MA.FACTSHIPMENT
SOURCE TABLES: BSL_STAGING.DWH_STAGING.SHIPMENT
DESCRIPTION: This model creates a fact table that tracks shipping details for orders including shipped and delivered dates and shipment status. It provides comprehensive shipment information for analytical purposes.
PREREQUISITES: Source table BSL_STAGING.DWH_STAGING.SHIPMENT must be available and populated
PARAMETER: Incremental model based on shipped_date
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

with shipment_data as (
    select
        order_id,
        shipped_date,
        delivery_date,
        status
    from {{ source('dwh_staging', 'shipment') }}
    {% if is_incremental() %}
        where shipped_date > (select max(shipped_date) from {{ this }})
    {% endif %}
)

select
    order_id,
    shipped_date,
    delivery_date,
    status
from shipment_data