{#
------------------------------------------------------------------------
MODEL NAME: FactPayment
TARGET TABLE: BSL_FINAL.DWH_MA.FACTPAYMENT
SOURCE TABLES: BSL_STAGING.DWH_STAGING.PAYMENT_TRANSACTION
DESCRIPTION: Records payment transactions for orders including payment amount and method. This model transforms staging payment data into the final fact table format.
PREREQUISITES: Source table BSL_STAGING.DWH_STAGING.PAYMENT_TRANSACTION must be available
PARAMETER: Incremental model with condition payment_date > max(payment_date)
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

with staging_data as (
    select
        order_id,
        payment_method,
        amount_paid,
        payment_ts
    from {{ source('dwh_staging', 'payment_transaction') }}
    {% if is_incremental() %}
        where date(payment_ts) > (select max(payment_date) from {{ this }})
    {% endif %}
),

final as (
    select
        order_id,
        payment_method,
        amount_paid,
        date(payment_ts) as payment_date
    from staging_data
)

select * from final