{#
------------------------------------------------------------------------
MODEL NAME: FactInventorySnapshot
TARGET TABLE: bsl_final.dwh_ma.FactInventorySnapshot
SOURCE TABLES: bsl_staging.dwh_staging.Inventory
DESCRIPTION: Daily snapshot of inventory quantities for each product in each warehouse location.
PREREQUISITES: Source table bsl_staging.dwh_staging.Inventory must be available and populated
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(materialized='view') }}

with inventory_snapshot as (
    select
        current_date() as snapshot_date,
        product_id,
        warehouse_id,
        quantity_on_hand
    from {{ source('dwh_staging', 'inventory') }}
)

select
    snapshot_date,
    product_id,
    warehouse_id,
    quantity_on_hand
from inventory_snapshot