{#
------------------------------------------------------------------------
MODEL NAME: FactReturns
TARGET TABLE: BSL_FINAL.DWH_MA.FACTRETURNS
SOURCE TABLES: BSL_STAGING.DWH_STAGING.RETURNS, BSL_STAGING.DWH_STAGING.ORDER_LINE
DESCRIPTION: Fact table that captures product return events with return date, return reason, and associated order line information. Includes product lookup from order line details.
PREREQUISITES: Order_Line table must be populated before running this model
PARAMETER: Incremental model with condition return_date > max(return_date)
AUTHOUR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_line_id'
) }}

with returns_staging as (
    select
        return_date,
        order_line_id,
        return_reason
    from {{ source('dwh_staging', 'returns') }}
    {% if is_incremental() %}
        where return_date > (select max(return_date) from {{ this }})
    {% endif %}
),

order_line_lookup as (
    select
        order_line_id,
        product_id
    from {{ source('dwh_staging', 'order_line') }}
),

final as (
    select
        rs.return_date as return_date,
        rs.order_line_id as order_line_id,
        ol.product_id as product_id,
        rs.return_reason as return_reason
    from returns_staging rs
    left join order_line_lookup ol
        on rs.order_line_id = ol.order_line_id
)

select * from final