{#
------------------------------------------------------------------------
MODEL NAME: fact_inventory
TARGET TABLE: BSL_MA.DWH_MA.FACT_INVENTORY
SOURCE TABLES: BSL_RAW.DWH_RAW.INVENTORY
DESCRIPTION: Inventory latest snapshot model that transforms raw inventory data with product and supplier lookups, data quality checks, and latest record flagging
PREREQUISITES: dim_product and dim_supplier models must exist
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

WITH source_data AS (
    SELECT 
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated
    FROM {{ source('dwh_raw', 'inventory') }}
),

-- Window function to identify latest records per product_id + supplier_id
latest_records AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (
            PARTITION BY product_id, supplier_id 
            ORDER BY last_updated DESC
        ) = 1 AS is_latest
    FROM source_data
),

-- Product lookup with fallback to unknown
product_lookup AS (
    SELECT 
        lr.*,
        COALESCE(dp.product_id, 0) AS mapped_product_id
    FROM latest_records lr
    LEFT JOIN {{ ref('dim_product') }} dp 
        ON lr.product_id = dp.product_id
),

-- Supplier lookup with fallback to unknown
supplier_lookup AS (
    SELECT 
        pl.*,
        COALESCE(ds.supplier_id, 0) AS mapped_supplier_id
    FROM product_lookup pl
    LEFT JOIN {{ ref('dim_supplier') }} ds 
        ON pl.supplier_id = ds.supplier_id
),

-- Final transformations
final AS (
    SELECT 
        mapped_product_id AS product_id,
        mapped_supplier_id AS supplier_id,
        -- Set negative stock quantities to null for data quality
        CASE 
            WHEN stock_qty < 0 THEN NULL 
            ELSE stock_qty 
        END AS stock_qty,
        UPPER(warehouse_location) AS warehouse_location,
        last_updated::DATE AS snapshot_date,
        is_latest
    FROM supplier_lookup
)

SELECT * FROM final