{#
------------------------------------------------------------------------
MODEL NAME: fact_inventory
TARGET TABLE: bsl_ma.dwh_ma.fact_inventory
SOURCE TABLES: bsl_raw.dwh_raw.inventory
DESCRIPTION: Inventory latest snapshot model that transforms raw inventory data with product and supplier lookups, data quality checks, and latest record flagging
PREREQUISITES: dim_product and dim_supplier models must exist
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

with source_data as (
    select 
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated
    from {{ source('dwh_raw', 'inventory') }}
),

-- Get latest record flag per product_id + supplier_id combination
latest_records as (
    select 
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated,
        case 
            when last_updated = max(last_updated) over (partition by product_id, supplier_id) 
            then true 
            else false 
        end as is_latest
    from source_data
),

-- Apply transformations and lookups
transformed as (
    select 
        -- Product ID lookup with fallback to 0 for unknown
        coalesce(dp.product_id, 0) as product_id,
        
        -- Supplier ID lookup with fallback to 0 for unknown  
        coalesce(ds.supplier_id, 0) as supplier_id,
        
        -- Stock quantity with negative value handling
        case 
            when lr.stock_qty < 0 then null 
            else lr.stock_qty 
        end as stock_qty,
        
        -- Uppercase warehouse location
        upper(lr.warehouse_location) as warehouse_location,
        
        -- Convert timestamp to date
        lr.last_updated::date as snapshot_date,
        
        -- Latest record flag
        lr.is_latest
        
    from latest_records lr
    
    -- Left join with dim_product for product_id lookup
    left join {{ ref('dim_product') }} dp 
        on lr.product_id = dp.product_id::varchar
    
    -- Left join with dim_supplier for supplier_id lookup  
    left join {{ ref('dim_supplier') }} ds 
        on lr.supplier_id = ds.supplier_id::varchar
)

select * from transformed