{#
------------------------------------------------------------------------
MODEL NAME: fact_inventory
TARGET TABLE: BSL_MA.DWH_MA.FACT_INVENTORY
SOURCE TABLES: BSL_RAW.DWH_RAW.INVENTORY
DESCRIPTION: Inventory latest snapshot model that transforms raw inventory data with product and supplier lookups, data quality checks, and latest record flagging
PREREQUISITES: dim_product and dim_supplier models must exist
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(materialized='table') }}

WITH inventory_base AS (
    SELECT 
        product_id,
        supplier_id,
        stock_qty,
        warehouse_location,
        last_updated
    FROM {{ source('dwh_raw', 'inventory') }}
),

inventory_transformed AS (
    SELECT 
        -- Product ID lookup with unknown handling
        COALESCE(dp.product_id, 0) AS product_id,
        
        -- Supplier ID lookup with unknown handling  
        COALESCE(ds.supplier_id, 0) AS supplier_id,
        
        -- Stock quantity with negative value handling
        CASE 
            WHEN ib.stock_qty < 0 THEN NULL
            ELSE ib.stock_qty
        END AS stock_qty,
        
        -- Warehouse location uppercase transformation
        UPPER(ib.warehouse_location) AS warehouse_location,
        
        -- Convert timestamp to date
        ib.last_updated::DATE AS snapshot_date,
        
        -- Keep original timestamp for latest record calculation
        ib.last_updated,
        
        -- Audit flag for negative stock quantities
        CASE 
            WHEN ib.stock_qty < 0 THEN TRUE
            ELSE FALSE
        END AS has_negative_stock_flag
        
    FROM inventory_base ib
    
    -- Left join with dim_product to lookup product_id
    LEFT JOIN {{ ref('dim_product') }} dp 
        ON ib.product_id = dp.product_id
    
    -- Left join with dim_supplier to lookup supplier_id  
    LEFT JOIN {{ ref('dim_supplier') }} ds
        ON ib.supplier_id = ds.supplier_id
),

inventory_with_latest_flag AS (
    SELECT 
        *,
        -- Flag latest record per product_id + supplier_id composite key
        CASE 
            WHEN last_updated = MAX(last_updated) OVER (
                PARTITION BY product_id, supplier_id
            ) THEN TRUE
            ELSE FALSE
        END AS is_latest
        
    FROM inventory_transformed
)

SELECT 
    product_id,
    supplier_id, 
    stock_qty,
    warehouse_location,
    snapshot_date,
    is_latest,
    has_negative_stock_flag
FROM inventory_with_latest_flag