{# ------------------------------------------------------------------------
MODEL NAME: FactPayment
TARGET TABLE: bsl_final.dwh_ma.FactPayment
SOURCE TABLES: bsl_staging.dwh_staging.Payment_Transaction
DESCRIPTION: This model creates the FactPayment table which records payment transactions for orders including payment amount and method. The model transforms payment transaction data from staging to the final fact table with date conversion for payment timestamp.
PREREQUISITES: Source table bsl_staging.dwh_staging.Payment_Transaction must be available and populated.
PARAMETER: Incremental load based on payment_date
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19
------------------------------------------------------------------------ #}

{{
    config(
        materialized='incremental',
        unique_key='order_id',
        schema='dwh_ma',
        database='bsl_final',
        alias='FactPayment'
    )
}}

with source_data as (
    select
        order_id,
        payment_method,
        amount_paid,
        payment_ts
    from {{ source('dwh_staging', 'payment_transaction') }}
    {% if is_incremental() %}
    where payment_ts::date > (select max(payment_date) from {{ this }})
    {% endif %}
),

transformed_data as (
    select
        order_id,
        payment_method,
        amount_paid,
        payment_ts::date as payment_date
    from source_data
)

select
    order_id,
    payment_method,
    amount_paid,
    payment_date
from transformed_data