{#
------------------------------------------------------------------------
MODEL NAME: FactPayment
TARGET TABLE: bsl_final.dwh_ma.FactPayment
SOURCE TABLES: bsl_staging.dwh_staging.Payment_Transaction
DESCRIPTION: This model creates a fact table for payment transactions, transforming staging data into a dimensional model format. It includes order payment details with payment methods, amounts, and converted date fields.
PREREQUISITES: Source table bsl_staging.dwh_staging.Payment_Transaction must be available and populated
PARAMETER: Incremental model based on payment_date
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

with payment_staging as (
    select
        order_id,
        payment_method,
        amount_paid,
        payment_ts
    from {{ source('dwh_staging', 'payment_transaction') }}
    {% if is_incremental() %}
        where payment_ts::date > (select max(payment_date) from {{ this }})
    {% endif %}
),

final as (
    select
        order_id,
        payment_method,
        amount_paid,
        payment_ts::date as payment_date
    from payment_staging
)

select * from final