{#
------------------------------------------------------------------------
MODEL NAME: FactShipment
TARGET TABLE: bsl_final.dwh_ma.FactShipment
SOURCE TABLES: bsl_staging.dwh_staging.shipment
DESCRIPTION: Tracks shipping details for orders including shipped and delivered dates and shipment status.
PREREQUISITES: Source table bsl_staging.dwh_staging.shipment must be available
PARAMETER: Incremental model with condition shipped_date > max(shipped_date)
AUTHOUR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

with source_data as (
    select
        order_id,
        shipped_date,
        delivery_date,
        status
    from {{ source('dwh_staging', 'shipment') }}
    {% if is_incremental() %}
        where shipped_date > (select max(shipped_date) from {{ this }})
    {% endif %}
),

final as (
    select
        order_id,
        shipped_date,
        delivery_date,
        status
    from source_data
)

select * from final