{#
------------------------------------------------------------------------
MODEL NAME: fact_shipment
TARGET TABLE: BSL_MA.DWH_MA.FACT_SHIPMENT
SOURCE TABLES: BSL_RAW.DWH_RAW.SHIPMENTS, BSL_MA.DWH_MA.FACT_ORDER
DESCRIPTION: Shipment fact table that transforms raw shipment data with surrogate keys, date conversions, and calculated shipping duration metrics
PREREQUISITES: fact_order table must exist for order_sk lookup
PARAMETER: Incremental model based on shipment_date
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='shipment_id'
) }}

with source_data as (
    select 
        shipment_id,
        order_id,
        shipment_date,
        order_date,
        carrier,
        tracking_number
    from {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        where shipment_date::date > (select coalesce(max(shipment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

order_lookup as (
    select 
        order_id,
        order_sk,
        order_date as order_order_date
    from {{ ref('fact_order') }}
),

transformed as (
    select
        -- Generate surrogate key from shipment_id
        {{ dbt_utils.generate_surrogate_key(['s.shipment_id']) }} as shipment_sk,
        
        -- Direct mapping of shipment_id
        s.shipment_id,
        
        -- Lookup order_sk from fact_order, skip if order missing
        o.order_sk,
        
        -- Convert timestamp to date
        s.shipment_date::date as shipment_date,
        
        -- Calculate days to ship with floor at 0 for negative values
        greatest(0, datediff('day', coalesce(o.order_order_date, s.order_date), s.shipment_date)) as days_to_ship,
        
        -- Uppercase carrier
        upper(s.carrier) as carrier,
        
        -- Direct mapping of tracking_number
        s.tracking_number
        
    from source_data s
    left join order_lookup o on s.order_id = o.order_id
)

select * from transformed