{#
------------------------------------------------------------------------
MODEL NAME: fact_order
TARGET TABLE: BSL_MA.DWH_MA.FACT_ORDER
SOURCE TABLES: BSL_RAW.DWH_RAW.ORDERS
DESCRIPTION: This model transforms raw order data into a fact table with proper data type conversions, status normalization, and customer validation through dimension lookup.
PREREQUISITES: dim_customer table must exist for customer lookup validation
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_id'
) }}

with source_data as (
    select 
        order_id,
        customer_id,
        order_date,
        status,
        total_amount
    from {{ source('dwh_raw', 'orders') }}
    {% if is_incremental() %}
        where order_date::date > (select coalesce(max(order_date), '1900-01-01') from {{ this }})
    {% endif %}
),

customer_lookup as (
    select 
        customer_id
    from {{ ref('dim_customer') }}
),

transformed_data as (
    select 
        s.order_id,
        s.customer_id,
        s.order_date::date as order_date,
        case 
            when upper(s.status) in ('PENDING', 'PAID', 'CANCELLED', 'SHIPPED') 
            then upper(s.status)
            else 'PENDING'
        end as order_status,
        case 
            when s.total_amount < 0 then null
            else s.total_amount::number(10,2)
        end as total_amount
    from source_data s
    inner join customer_lookup c
        on s.customer_id = c.customer_id
)

select 
    order_id,
    customer_id,
    order_date,
    order_status,
    total_amount
from transformed_data