{# ------------------------------------------------------------------------
MODEL NAME: FactSales
TARGET TABLE: bsl_final.dwh_ma.FactSales
SOURCE TABLES: bsl_staging.dwh_staging.Order_Header, bsl_staging.dwh_staging.Order_Line, bsl_staging.dwh_staging.Product_Discount
DESCRIPTION: Line-level sales fact capturing quantities sold and financial metrics per product and order line. This model combines order header and line details with product discount information to calculate gross amounts, discount amounts, and net amounts for each sales transaction.
PREREQUISITES: Source tables Order_Header, Order_Line, and Product_Discount must be available in bsl_staging.dwh_staging schema.
PARAMETER: Incremental load based on order_date where order_date > max(order_date)
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2025-01-09
------------------------------------------------------------------------ #}

{{ config(
    materialized='incremental',
    unique_key='order_line_id',
    incremental_strategy='merge'
) }}

with order_header as (
    select
        order_id,
        order_date,
        customer_id
    from {{ source('dwh_staging', 'order_header') }}
    {% if is_incremental() %}
    where order_date > (select max(order_date) from {{ this }})
    {% endif %}
),

order_line as (
    select
        order_line_id,
        order_id,
        product_id,
        quantity,
        unit_price
    from {{ source('dwh_staging', 'order_line') }}
),

product_discount as (
    select
        product_id,
        discount_pct
    from {{ source('dwh_staging', 'product_discount') }}
),

joined_data as (
    select
        oh.order_date,
        oh.customer_id,
        ol.product_id,
        oh.order_id,
        ol.order_line_id,
        ol.quantity,
        ol.unit_price,
        coalesce(pd.discount_pct, 0) as discount_pct
    from order_line ol
    inner join order_header oh
        on ol.order_id = oh.order_id
    left join product_discount pd
        on ol.product_id = pd.product_id
),

final as (
    select
        order_date,
        customer_id,
        product_id,
        order_id,
        order_line_id,
        quantity as quantity_sold,
        (quantity * unit_price) as gross_amount,
        (unit_price * discount_pct) as discount_amount,
        ((quantity * unit_price) - (unit_price * discount_pct)) as net_amount
    from joined_data
)

select * from final