{#
------------------------------------------------------------------------
MODEL NAME: fact_payment
TARGET TABLE: bsl_ma.dwh_ma.fact_payment
SOURCE TABLES: bsl_raw.dwh_raw.payments
DESCRIPTION: Payment fact table at payment event level with transformed payment data including surrogate keys and business logic
PREREQUISITES: fact_order table must exist for order_sk lookup
PARAMETER: Incremental model based on payment_date
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='payment_id'
) }}

with source_data as (
    select * from {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
        where payment_date::date > (select coalesce(max(payment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

order_lookup as (
    select 
        order_id,
        order_sk,
        total_amount
    from {{ ref('fact_order') }}
),

payment_aggregates as (
    select 
        order_id,
        sum(case when amount >= 0 then amount else 0 end) as total_payments
    from source_data
    group by order_id
),

transformed as (
    select
        -- Generate surrogate key from payment_id
        {{ dbt_utils.generate_surrogate_key(['s.payment_id']) }} as payment_sk,
        
        -- Direct mapping of payment_id
        s.payment_id,
        
        -- Lookup order_sk from fact_order
        o.order_sk,
        
        -- Convert timestamp to date
        s.payment_date::date as payment_date,
        
        -- Uppercase and map payment method to enum
        case 
            when upper(s.payment_method) in ('CARD', 'UPI', 'COD', 'NETBANKING') 
            then upper(s.payment_method)
            else 'CARD'
        end as payment_method,
        
        -- Handle negative amounts
        case 
            when s.amount < 0 then null
            else s.amount
        end as amount,
        
        -- Calculate is_fully_applied flag
        case 
            when o.total_amount is null then false
            when pa.total_payments >= o.total_amount then true
            else false
        end as is_fully_applied
        
    from source_data s
    inner join order_lookup o on s.order_id = o.order_id
    left join payment_aggregates pa on s.order_id = pa.order_id
    -- Skip payments if order not present (inner join handles this)
)

select * from transformed