{#
------------------------------------------------------------------------
MODEL NAME: fact_order_item
TARGET TABLE: BSL_MA.DWH_MA.FACT_ORDER_ITEM
SOURCE TABLES: BSL_RAW.DWH_RAW.ORDER_ITEMS
DESCRIPTION: Fact table for order items containing order details, product information, quantities, pricing, and calculated amounts including extended amount, discount allocation, and net amount
PREREQUISITES: fact_order and dim_product tables must exist and be populated
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_item_id'
) }}

WITH source_data AS (
    SELECT 
        order_id,
        product_id,
        quantity,
        unit_price,
        order_item_id
    FROM {{ source('dwh_raw', 'order_items') }}
    {% if is_incremental() %}
    WHERE exists (select 1 where true) and {{ is_incremental() }}
    {% endif %}
),

order_lookup AS (
    SELECT DISTINCT order_id
    FROM {{ ref('fact_order') }}
),

product_lookup AS (
    SELECT 
        product_id,
        COALESCE(product_sk, 0) AS product_sk
    FROM {{ ref('dim_product') }}
),

transformed_data AS (
    SELECT 
        -- Order ID lookup and conversion
        CAST(s.order_id AS INTEGER) AS order_id,
        
        -- Product ID lookup and conversion
        CAST(s.product_id AS INTEGER) AS product_id,
        COALESCE(p.product_sk, 0) AS product_sk,
        
        -- Direct mappings with data type conversions
        ROUND(s.quantity) AS quantity,
        CAST(s.unit_price AS NUMBER(10,2)) AS unit_price,
        
        -- Calculated extended amount
        CAST(ROUND(s.quantity) * COALESCE(s.unit_price, 0) AS NUMBER(12,2)) AS extended_amount,
        
        -- Discount amount allocation (set to 0 as no discount context available)
        CAST(0 AS NUMBER(12,2)) AS discount_amount,
        
        -- Net amount calculation (extended_amount - discount_amount, floored at 0)
        CAST(GREATEST(0, ROUND(s.quantity) * COALESCE(s.unit_price, 0) - 0) AS NUMBER(12,2)) AS net_amount,
        
        s.order_item_id
        
    FROM source_data s
    INNER JOIN order_lookup o ON s.order_id = o.order_id  -- Skip items if order_id missing in fact_order
    LEFT JOIN product_lookup p ON s.product_id = p.product_id  -- Left join to handle missing products with product_sk = 0
)

SELECT 
    order_id,
    product_id,
    product_sk,
    quantity,
    unit_price,
    extended_amount,
    discount_amount,
    net_amount,
    order_item_id
FROM transformed_data