{#
------------------------------------------------------------------------
MODEL NAME: fact_shipment
TARGET TABLE: bsl_ma.dwh_ma.fact_shipment
SOURCE TABLES: bsl_raw.dwh_raw.shipments
DESCRIPTION: This model transforms raw shipment data into a fact table for analytics. It includes shipment details, order lookups, and calculated metrics like days to ship.
PREREQUISITES: fact_order table must exist for order_id lookups
PARAMETER: None
AUTHOR: AI Generated by Shajahan
CREATED DATE: 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='shipment_id'
) }}

with source_data as (
    select 
        shipment_id,
        order_id as source_order_id,
        shipment_date,
        order_date,
        carrier,
        tracking_number
    from {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        where shipment_date::date > (select coalesce(max(shipment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

order_lookup as (
    select 
        order_id,
        order_date as fact_order_date
    from {{ ref('fact_order') }}
),

final as (
    select 
        s.shipment_id,
        o.order_id,
        s.shipment_date::date as shipment_date,
        greatest(0, datediff('day', coalesce(o.fact_order_date, s.order_date), s.shipment_date)) as days_to_ship,
        upper(s.carrier) as carrier,
        s.tracking_number
    from source_data s
    left join order_lookup o 
        on s.source_order_id = o.order_id::varchar
    where o.order_id is not null  -- Skip if order missing
)

select * from final