{#
------------------------------------------------------------------------
MODEL NAME: fact_shipment
TARGET TABLE: bsl_ma.dwh_ma.fact_shipment
SOURCE TABLES: bsl_raw.dwh_raw.shipments, bsl_raw.dwh_raw.orders
DESCRIPTION: Fact table for shipment data with order details and calculated shipping metrics
PREREQUISITES: fact_order table must exist for order lookups
PARAMETER: None
AUTHOUR: AI Generated by Shajahan - 2024-12-19 IST
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    schema = 'dwh_ma',
    alias = 'fact_shipment',
    unique_key = 'shipment_id'
) }}

WITH shipments_source AS (
    SELECT
        shipment_id,
        order_id,
        shipped_date,
        carrier,
        tracking_number
    FROM {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        WHERE shipped_date::date > (select coalesce(max(shipped_date), '1900-01-01') from {{ this }})
    {% endif %}
),

orders_source AS (
    SELECT
        order_id,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
),

fact_order_lookup AS (
    SELECT
        order_id
    FROM {{ ref('fact_order') }}
),

transformed AS (
    SELECT
        s.shipment_id,
        s.order_id,
        s.shipped_date::date as shipped_date,
        UPPER(s.carrier) as carrier,
        s.tracking_number,
        -- Calculate days to ship with floor at 0 for negative values
        GREATEST(0, DATEDIFF('day', o.order_date, s.shipped_date)) as days_to_ship
    FROM shipments_source s
    LEFT JOIN orders_source o ON s.order_id = o.order_id
    INNER JOIN fact_order_lookup fo ON s.order_id = fo.order_id  -- Skip if order missing
)

SELECT * FROM transformed