{#
------------------------------------------------------------------------
MODEL NAME: fact_payment
TARGET TABLE: bsl_ma.dwh_ma.fact_payment
SOURCE TABLES: bsl_raw.dwh_raw.payments, bsl_ma.dwh_ma.fact_order
DESCRIPTION: This model transforms raw payment data into a fact table with proper data types, validation, and business logic. It includes payment method standardization, order validation, and payment application status calculation.
PREREQUISITES: fact_order model must exist and be populated
PARAMETER: None
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='payment_id'
) }}

with source_payments as (
    select 
        payment_id,
        order_id,
        payment_date,
        payment_method,
        amount
    from {{ source('dwh_raw', 'payments') }}
    {% if is_incremental() %}
        where payment_date::date > (select coalesce(max(payment_date), '1900-01-01') from {{ this }})
    {% endif %}
),

fact_order_ref as (
    select 
        order_id,
        total_amount
    from {{ ref('fact_order') }}
),

payments_with_order_validation as (
    select 
        sp.payment_id,
        sp.order_id,
        sp.payment_date::date as payment_date,
        sp.payment_method,
        sp.amount,
        fo.total_amount as order_total_amount
    from source_payments sp
    inner join fact_order_ref fo 
        on sp.order_id = fo.order_id
),

payment_method_standardized as (
    select 
        payment_id,
        order_id,
        payment_date,
        case 
            when upper(payment_method) in ('CARD', 'UPI', 'COD', 'NETBANKING') 
            then upper(payment_method)
            else 'CARD'
        end as payment_method,
        case 
            when amount < 0 then null
            else amount
        end as amount,
        order_total_amount
    from payments_with_order_validation
),

payment_aggregation as (
    select 
        order_id,
        sum(coalesce(amount, 0)) as total_payments
    from payment_method_standardized
    group by order_id
),

final as (
    select 
        pms.payment_id,
        pms.order_id,
        pms.payment_date,
        pms.payment_method,
        pms.amount::number(10,2) as amount,
        case 
            when pms.order_total_amount is null then false
            when pa.total_payments >= pms.order_total_amount then true
            else false
        end as is_fully_applied
    from payment_method_standardized pms
    left join payment_aggregation pa 
        on pms.order_id = pa.order_id
)

select * from final