{#
------------------------------------------------------------------------
MODEL NAME: fact_shipment
TARGET TABLE: bsl_ma.dwh_ma.fact_shipment
SOURCE TABLES: bsl_raw.dwh_raw.shipments, bsl_raw.dwh_raw.orders
DESCRIPTION: This model creates a fact table for shipments by combining shipment data with order information to calculate shipping metrics and standardize carrier information.
PREREQUISITES: fact_order model must exist for order_id lookup
PARAMETER: Incremental model based on shipment_date
AUTHOR: AI Generated by Shajahan - 2024-12-19
------------------------------------------------------------------------
#}

{{ config(
    materialized = 'incremental',
    alias = 'fact_shipment'
) }}

WITH source_shipments AS (
    SELECT
        shipment_id,
        order_id,
        shipped_date,
        carrier,
        tracking_number
    FROM {{ source('dwh_raw', 'shipments') }}
    {% if is_incremental() %}
        WHERE shipped_date::date > (select coalesce(max(shipped_date), '1900-01-01') from {{ this }})
    {% endif %}
),

source_orders AS (
    SELECT
        order_id,
        order_date
    FROM {{ source('dwh_raw', 'orders') }}
),

joined_data AS (
    SELECT
        s.shipment_id,
        s.order_id,
        s.shipped_date,
        s.carrier,
        s.tracking_number,
        o.order_date
    FROM source_shipments s
    INNER JOIN source_orders o
        ON s.order_id = o.order_id
),

transformed AS (
    SELECT
        shipment_id AS fs_shipment_id,
        order_id AS fs_order_id,
        shipped_date::date AS fs_shipped_date,
        UPPER(carrier) AS fs_carrier,
        tracking_number AS fs_tracking_number,
        GREATEST(0, DATEDIFF('day', order_date::date, shipped_date::date)) AS fs_days_to_ship
    FROM joined_data
)

SELECT * FROM transformed