{#
------------------------------------------------------------------------
MODEL NAME: FactSales
TARGET TABLE: BSL_FINAL.DWH_MA.FACTSALES
SOURCE TABLES: BSL_STAGING.DWH_STAGING.ORDER_HEADER, BSL_STAGING.DWH_STAGING.ORDER_LINE, BSL_STAGING.DWH_STAGING.PRODUCT_DISCOUNT
DESCRIPTION: Line-level sales fact capturing quantities sold and financial metrics per product and order line.
PREREQUISITES: Order_Header, Order_Line, and Product_Discount tables must be available in staging
PARAMETER: Incremental model based on order_date
AUTHOUR: AI Generated by Shajahan - 2024-12-19 (IST)
------------------------------------------------------------------------
#}

{{ config(
    materialized='incremental',
    unique_key='order_line_id'
) }}

with order_header as (
    select 
        order_id,
        order_date,
        customer_id
    from {{ source('dwh_staging', 'order_header') }}
    {% if is_incremental() %}
        where order_date > (select max(order_date) from {{ this }})
    {% endif %}
),

order_line as (
    select 
        order_line_id,
        order_id,
        product_id,
        quantity,
        unit_price
    from {{ source('dwh_staging', 'order_line') }}
),

product_discount as (
    select 
        product_id,
        discount_pct
    from {{ source('dwh_staging', 'product_discount') }}
),

final as (
    select 
        oh.order_date,
        oh.customer_id,
        ol.product_id,
        oh.order_id,
        ol.order_line_id,
        ol.quantity as quantity_sold,
        (ol.quantity * ol.unit_price) as gross_amount,
        (ol.unit_price * coalesce(pd.discount_pct, 0)) as discount_amount,
        ((ol.quantity * ol.unit_price) - (ol.unit_price * coalesce(pd.discount_pct, 0))) as net_amount
    from order_header oh
    inner join order_line ol 
        on oh.order_id = ol.order_id
    left join product_discount pd 
        on ol.product_id = pd.product_id
)

select * from final