version: 2

models:
  - name: dim_address
    description: Dimension table containing customer address information with standardized formatting
    columns:
      - name: address_id
        description: Unique identifier for each address record
      - name: customer_id
        description: Foreign key linking to customer dimension table
      - name: address_line1
        description: Primary address line with whitespace trimmed
      - name: city
        description: City name in uppercase format
      - name: country
        description: Country name for the address
      - name: inserted_at
        description: Date when the address record was created

  - name: dim_category
    description: Dimension table for product categories with hierarchical structure
    columns:
      - name: category_id
        description: Unique identifier for each category
      - name: category_name
        description: Category name in title case format
      - name: parent_category_id
        description: Reference to parent category for hierarchical structure
      - name: category_path
        description: Full category path showing hierarchy up to 2 levels
      - name: is_active
        description: Boolean flag indicating if category is currently active

  - name: dim_customer
    description: Dimension table containing customer information with derived spending tiers
    columns:
      - name: customer_id
        description: Unique identifier for each customer
      - name: first_name
        description: Customer first name in uppercase format
      - name: last_name
        description: Customer last name in uppercase format
      - name: email
        description: Customer email address in lowercase format
      - name: customer_since_date
        description: Date when customer first registered
      - name: customer_tier
        description: Spending tier classification based on order history (Gold/Silver/Bronze)

  - name: dim_product
    description: Dimension table for products with pricing information and categorization
    columns:
      - name: product_id
        description: Unique identifier for each product
      - name: product_name
        description: Product name in title case format
      - name: category_id
        description: Foreign key linking to category dimension
      - name: price
        description: Product price with decimal precision
      - name: price_band
        description: Price classification bucket (Low/Mid/High/Premium)

  - name: dim_supplier
    description: Dimension table containing supplier information and contact details
    columns:
      - name: supplier_id
        description: Unique identifier for each supplier
      - name: supplier_name
        description: Supplier name in title case format
      - name: contact_email
        description: Supplier contact email in lowercase format
      - name: country
        description: Supplier country in uppercase format
      - name: is_active
        description: Boolean flag indicating if supplier is currently active

  - name: fact_inventory
    description: Fact table tracking inventory levels by product and supplier with snapshot capabilities
    columns:
      - name: product_id
        description: Foreign key linking to product dimension
      - name: supplier_id
        description: Foreign key linking to supplier dimension
      - name: stock_qty
        description: Current stock quantity available
      - name: warehouse_location
        description: Warehouse location in uppercase format
      - name: snapshot_date
        description: Date of inventory snapshot
      - name: is_latest
        description: Boolean flag indicating the most recent inventory record per product-supplier combination

  - name: fact_order
    description: Fact table containing order header information with standardized status values
    columns:
      - name: order_id
        description: Unique identifier for each order
      - name: customer_id
        description: Foreign key linking to customer dimension
      - name: order_date
        description: Date when order was placed
      - name: ORDER_status
        description: Normalized order status (PENDING/PAID/CANCELLED/SHIPPED)
      - name: total_amount
        description: Total order amount with decimal precision

  - name: fact_order_item
    description: Fact table containing individual order line items with calculated amounts
    columns:
      - name: order_id
        description: Foreign key linking to order fact table
      - name: product_id
        description: Foreign key linking to product dimension
      - name: quantity
        description: Quantity of product ordered
      - name: unit_price
        description: Price per unit of product
      - name: extended_amount
        description: Calculated total amount (quantity × unit_price)
      - name: discount_amount
        description: Proportionally allocated discount amount
      - name: net_amount
        description: Final amount after discount (extended_amount - discount_amount)

  - name: fact_payment
    description: Fact table tracking payment transactions with payment method standardization
    columns:
      - name: payment_id
        description: Unique identifier for each payment transaction
      - name: order_id
        description: Foreign key linking to order fact table
      - name: payment_date
        description: Date when payment was processed
      - name: payment_method
        description: Standardized payment method (CARD/UPI/COD/NETBANKING)
      - name: amount
        description: Payment amount with decimal precision
      - name: is_fully_applied
        description: Boolean flag indicating if total payments cover full order amount

  - name: fact_shipment
    description: Fact table containing shipment information with delivery performance metrics
    columns:
      - name: shipment_id
        description: Unique identifier for each shipment
      - name: order_id
        description: Foreign key linking to order fact table
      - name: shipment_date
        description: Date when shipment was dispatched
      - name: days_to_ship
        description: Number of days between order date and shipment date
      - name: carrier
        description: Shipping carrier name in uppercase format
      - name: tracking_number
        description: Shipment tracking number for delivery monitoring