version: 2
models:
  - name: customers
    schema: staging
    columns:
      - name: customer_id
        type: string
        description: Direct mapping from cust_id
        tests:
          - not_null
          - unique
      - name: full_name
        type: string
        description: Concatenate first_name and last_name
        tests:
          - not_null
      - name: signup_month
        type: string
        description: Extract month name from signup_date
        tests:
          - not_null
      - name: is_vip
        type: boolean
        description: Convert Y/N to TRUE/FALSE
        tests:
          - not_null

  - name: employees
    schema: staging
    columns:
      - name: employee_id
        type: string
        description: Direct mapping from emp_id
        tests:
          - not_null
          - unique
      - name: annual_bonus
        type: float
        description: Calculate 15% of salary as annual bonus
        tests:
          - not_null

  - name: inventory_summary
    schema: staging
    columns:
      - name: product_id
        type: string
        description: Direct mapping from product_id
        tests:
          - not_null
          - unique
      - name: stock_status
        type: string
        description: If quantity > 0 then 'IN_STOCK' else 'OUT_OF_STOCK'
        tests:
          - not_null

  - name: orders
    schema: staging
    columns:
      - name: order_id
        type: string
        description: Direct mapping from order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        type: string
        description: Direct mapping from customer_id
        tests:
          - not_null
      - name: order_week
        type: string
        description: Derive ISO week from order_date
        tests:
          - not_null
      - name: total_amount_usd
        type: float
        description: Convert from local_currency using exchange_rate table
        tests:
          - not_null

  - name: payments
    schema: staging
    columns:
      - name: payment_id
        type: string
        description: Direct mapping from payment_id
        tests:
          - not_null
          - unique
      - name: payment_category
        type: string
        description: Categorize as 'Card','Wallet','Cash' based on payment_mode value
        tests:
          - not_null

  - name: products
    schema: staging
    columns:
      - name: product_id
        type: string
        description: Direct mapping from product_id
        tests:
          - not_null
          - unique
      - name: discounted_price
        type: float
        description: Apply 10% discount if category = 'Seasonal'
        tests:
          - not_null

  - name: reviews
    schema: staging
    columns:
      - name: review_id
        type: string
        description: Direct mapping from review_id
        tests:
          - not_null
          - unique
      - name: sentiment_category
        type: string
        description: If rating