version: 2

models:
  - name: customers
    description: Staging model for customer data with transformed names and VIP status
    columns:
      - name: customer_id
        description: Unique identifier for each customer
        tests:
          - not_null
          - unique
      - name: full_name
        description: Customer's full name concatenated from first and last name
        tests:
          - not_null
      - name: signup_month
        description: Month name extracted from customer signup date
        tests:
          - not_null
      - name: is_vip
        description: Boolean flag indicating VIP customer status
        tests:
          - not_null

  - name: employees
    description: Staging model for employee data with calculated annual bonus
    columns:
      - name: employee_id
        description: Unique identifier for each employee
        tests:
          - not_null
          - unique
      - name: annual_bonus
        description: Annual bonus calculated as 15% of employee salary
        tests:
          - not_null

  - name: inventory_summary
    description: Staging model for inventory data with stock status categorization
    columns:
      - name: product_id
        description: Unique identifier for each product
        tests:
          - not_null
          - unique
      - name: stock_status
        description: Stock availability status based on quantity
        tests:
          - not_null
          - accepted_values:
              values: ['IN_STOCK', 'OUT_OF_STOCK']

  - name: orders
    description: Staging model for order data with week derivation and currency conversion
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Foreign key reference to customer
        tests:
          - not_null
      - name: order_week
        description: ISO week number derived from order date
        tests:
          - not_null
      - name: total_amount_usd
        description: Order total amount converted from INR to USD
        tests:
          - not_null

  - name: payments
    description: Staging model for payment data with categorized payment methods
    columns:
      - name: payment_id
        description: Unique identifier for each payment
        tests:
          - not_null
          - unique
      - name: payment_category
        description: Categorized payment method type
        tests:
          - not_null
          - accepted_values:
              values: ['Card', 'Wallet', 'Cash']

  - name: products
    description: Staging model for product data with conditional discount pricing
    columns:
      - name: product_id
        description: Unique identifier for each product
        tests:
          - not_null
          - unique
      - name: discounted_price
        description: Product price with 10% discount applied for seasonal items
        tests:
          - not_null

  - name: reviews
    description: Staging model for review data with sentiment categorization
    columns:
      - name: review_id
        description: Unique identifier for each review
        tests:
          - not_null
          - unique
      - name: sentiment_category
        description: Sentiment category based on rating score
        tests:
          - not_null
          - accepted_values:
              values: ['Positive', 'Neutral', 'Negative']

  - name: shipments
    description: Staging model for shipment data with delivery delay calculation
    columns:
      - name: shipment_id
        description: Unique identifier for each shipment
        tests:
          - not_null
          - unique
      - name: delivery_delay_days
        description: Number of days between order date and delivery date
        tests:
          - not_null

  - name: transactions
    description: Staging model for transaction data with tax calculation
    columns:
      - name: transaction_id
        description: Unique identifier for each transaction
        tests:
          - not_null
          - unique
      - name: amount_with_tax
        description: Transaction amount with 18% GST added
        tests:
          - not_null

  - name: web_sessions
    description: Staging model for web session data with time and domain extraction
    columns:
      - name: session_id
        description: Unique identifier for each web session
        tests:
          - not_null
          - unique
      - name: session_hour
        description: Hour extracted from session timestamp
        tests:
          - not_null
      - name: domain_name
        description: Domain name extracted from session URL
        tests:
          - not_null