version: 2

sources:
  - name: dwh_staging
    database: bsl_staging
    schema: dwh_staging
    tables:
      - name: Address
        description: "Address information including city, state, and country. Join customer_address to get address_id and join address to get the country."
        columns:
          - name: city
            description: "City name"
          - name: state
            description: "State name"
          - name: country
            description: "Country name - lookup based on customer_id"

      - name: Customer
        description: "Customer information. Customer is active only if the created_ts is less than 2 years from current_date."
        columns:
          - name: customer_id
            description: "Unique customer identifier"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: phone
            description: "Customer phone number"
          - name: created_ts
            description: "Customer creation timestamp"

      - name: Customer_Address
        description: "Bridge table to join customer and address tables"

      - name: Inventory
        description: "Product inventory information by warehouse"
        columns:
          - name: quantity_on_hand
            description: "Current quantity available"
          - name: product_id
            description: "Product identifier"
          - name: warehouse_id
            description: "Warehouse identifier"

      - name: Order_Header
        description: "Order header information"
        columns:
          - name: order_date
            description: "Date when order was placed"
          - name: customer_id
            description: "Customer identifier"
          - name: order_id
            description: "Unique order identifier"

      - name: Order_Line
        description: "Order line items. Lookup product_id based on order_line_id."
        columns:
          - name: product_id
            description: "Product identifier"
          - name: order_line_id
            description: "Unique order line identifier"
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Unit price of product"

      - name: Payment_Transaction
        description: "Payment transaction details. Convert payment_ts to date."
        columns:
          - name: order_id
            description: "Order identifier"
          - name: payment_method
            description: "Method of payment"
          - name: amount_paid
            description: "Amount paid"
          - name: payment_ts
            description: "Payment timestamp"

      - name: Product
        description: "Product master data"
        columns:
          - name: product_id
            description: "Unique product identifier"
          - name: product_name
            description: "Product name"
          - name: brand
            description: "Product brand"

      - name: Product_Category
        description: "Product category information. Lookup category_name based on product_category_id."
        columns:
          - name: category_name
            description: "Category name"

      - name: Product_Discount
        description: "Product discount information. Lookup discount_pct and calculate discounted price. Consider the discount effective_from and effective_to dates."

      - name: Returns
        description: "Product return information"
        columns:
          - name: return_date
            description: "Date of return"
          - name: order_line_id
            description: "Order line identifier"
          - name: return_reason
            description: "Reason for return"

      - name: Shipment
        description: "Shipment tracking information"
        columns:
          - name: order_id
            description: "Order identifier"
          - name: shipped_date
            description: "Date when order was shipped"
          - name: delivery_date
            description: "Date when order was delivered"
          - name: status
            description: "Shipment status"