version: 2

sources:
  - name: dwh_staging
    database: bsl_staging
    schema: dwh_staging
    description: "Staging tables from the data warehouse"
    tables:
      - name: address
        description: "Address information"
        columns:
          - name: city
            description: "City name"
          - name: state
            description: "State or province"
          - name: country
            description: "Country name"

      - name: customer
        description: "Customer master data"
        columns:
          - name: customer_id
            description: "Unique customer identifier"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: phone
            description: "Customer phone number"
          - name: created_ts
            description: "Customer creation timestamp"

      - name: inventory
        description: "Product inventory levels"
        columns:
          - name: quantity_on_hand
            description: "Current inventory quantity"
          - name: product_id
            description: "Product identifier"
          - name: warehouse_id
            description: "Warehouse identifier"

      - name: order_header
        description: "Order header information"
        columns:
          - name: order_date
            description: "Date order was placed"
          - name: customer_id
            description: "Customer who placed the order"
          - name: order_id
            description: "Unique order identifier"

      - name: order_line
        description: "Order line items"
        columns:
          - name: product_id
            description: "Product identifier"
          - name: order_line_id
            description: "Unique order line identifier"
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Price per unit"

      - name: payment_transaction
        description: "Payment transaction records"
        columns:
          - name: order_id
            description: "Associated order identifier"
          - name: payment_method
            description: "Method of payment"
          - name: amount_paid
            description: "Amount paid"
          - name: payment_ts
            description: "Payment timestamp"

      - name: product
        description: "Product master data"
        columns:
          - name: product_id
            description: "Unique product identifier"
          - name: product_name
            description: "Product name"
          - name: brand
            description: "Product brand"
          - name: unit_price
            description: "Product unit price"

      - name: product_category
        description: "Product category information"
        columns:
          - name: category_name
            description: "Category name"

      - name: returns
        description: "Product return records"
        columns:
          - name: return_date
            description: "Date of return"
          - name: order_line_id
            description: "Associated order line identifier"
          - name: return_reason
            description: "Reason for return"

      - name: shipment
        description: "Order shipment information"
        columns:
          - name: order_id
            description: "Associated order identifier"
          - name: shipped_date
            description: "Date order was shipped"
          - name: delivery_date
            description: "Date order was delivered"
          - name: status
            description: "Shipment status"