version: 2

sources:
  - name: dwh_staging
    database: bsl_staging
    schema: dwh_staging
    description: "Staging tables for data warehouse"
    tables:
      - name: address
        description: "Address information for customers"
        columns:
          - name: city
            description: "City name"
          - name: state
            description: "State or province"
          - name: country
            description: "Country name"
          - name: address_id
            description: "Unique identifier for address"

      - name: customer
        description: "Customer master data"
        columns:
          - name: customer_id
            description: "Unique identifier for customer"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: phone
            description: "Customer phone number"
          - name: created_ts
            description: "Timestamp when customer was created"

      - name: customer_address
        description: "Junction table linking customers to addresses"
        columns:
          - name: customer_id
            description: "Reference to customer"
          - name: address_id
            description: "Reference to address"

      - name: inventory
        description: "Product inventory levels by warehouse"
        columns:
          - name: quantity_on_hand
            description: "Available quantity in stock"
          - name: product_id
            description: "Reference to product"
          - name: warehouse_id
            description: "Reference to warehouse"

      - name: order_header
        description: "Order header information"
        columns:
          - name: order_date
            description: "Date when order was placed"
          - name: customer_id
            description: "Reference to customer who placed order"
          - name: order_id
            description: "Unique identifier for order"

      - name: order_line
        description: "Individual line items within orders"
        columns:
          - name: product_id
            description: "Reference to ordered product"
          - name: order_line_id
            description: "Unique identifier for order line"
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Price per unit"

      - name: payment_transaction
        description: "Payment transactions for orders"
        columns:
          - name: order_id
            description: "Reference to order"
          - name: payment_method
            description: "Method of payment used"
          - name: amount_paid
            description: "Amount paid in transaction"
          - name: payment_ts
            description: "Timestamp of payment"

      - name: product
        description: "Product master data"
        columns:
          - name: product_id
            description: "Unique identifier for product"
          - name: product_name
            description: "Name of the product"
          - name: brand
            description: "Brand of the product"

      - name: product_category
        description: "Product category information"
        columns:
          - name: product_category_id
            description: "Unique identifier for product category"
          - name: category_name
            description: "Name of the product category"

      - name: product_discount
        description: "Product discount information with effective dates"
        columns:
          - name: discount_pct
            description: "Discount percentage"
          - name: effective_from
            description: "Start date for discount validity"
          - name: effective_to
            description: "End date for discount validity"

      - name: returns
        description: "Product return information"
        columns:
          - name: return_date
            description: "Date when product was returned"
          - name: order_line_id
            description: "Reference to original order line"
          - name: return_reason
            description: "Reason for return"

      - name: shipment
        description: "Order shipment tracking information"
        columns:
          - name: order_id
            description: "Reference to order"
          - name: shipped_date
            description: "Date when order was shipped"
          - name: delivery_date
            description: "Date when order was delivered"
          - name: status
            description: "Current shipment status"