version: 2

sources:
  - name: raw
    database: demo_db
    schema: raw
    description: "Raw source data from various systems"
    
    tables:
      - name: raw_customers
        description: "Customer information and profile data"
        columns:
          - name: cust_id
            description: "Unique customer identifier"
            tests:
              - unique
              - not_null
          - name: first_name
            description: "Customer first name"
          - name: signup_date
            description: "Date when customer signed up"
          - name: is_vip_flag
            description: "Flag indicating VIP customer status"

      - name: raw_employees
        description: "Employee information and compensation data"
        columns:
          - name: emp_id
            description: "Unique employee identifier"
            tests:
              - unique
              - not_null
          - name: salary
            description: "Employee salary amount"

      - name: raw_inventory
        description: "Product inventory levels"
        columns:
          - name: product_id
            description: "Unique product identifier"
            tests:
              - not_null
          - name: quantity
            description: "Available product quantity"

      - name: raw_orders
        description: "Customer order transactions"
        columns:
          - name: order_id
            description: "Unique order identifier"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Reference to customer who placed the order"
            tests:
              - not_null
          - name: order_date
            description: "Date when order was placed"
          - name: total_amount
            description: "Total order amount"

      - name: raw_payments
        description: "Payment transaction details"
        columns:
          - name: payment_id
            description: "Unique payment identifier"
            tests:
              - unique
              - not_null
          - name: payment_mode
            description: "Method of payment used"

      - name: raw_products
        description: "Product catalog and pricing information"
        columns:
          - name: product_id
            description: "Unique product identifier"
            tests:
              - unique
              - not_null
          - name: price
            description: "Product price"

      - name: raw_reviews
        description: "Customer product reviews and ratings"
        columns:
          - name: review_id
            description: "Unique review identifier"
            tests:
              - unique
              - not_null
          - name: rating
            description: "Customer rating score"

      - name: raw_shipments
        description: "Order shipment and delivery information"
        columns:
          - name: shipment_id
            description: "Unique shipment identifier"
            tests:
              - unique
              - not_null
          - name: delivery_date
            description: "Date when shipment was delivered"

      - name: raw_transactions
        description: "Financial transaction records"
        columns:
          - name: transaction_id
            description: "Unique transaction identifier"
            tests:
              - unique
              - not_null
          - name: amount
            description: "Transaction amount"

      - name: raw_web_logs
        description: "Website user activity logs"
        columns:
          - name: session_id
            description: "User session identifier"
            tests:
              - not_null
          - name: timestamp
            description: "Timestamp of web activity"
          - name: url
            description: "URL accessed by user"