version: 2

sources:
  - name: dwh_staging
    database: bsl_staging
    schema: dwh_staging
    description: "Staging tables for data warehouse processing"
    tables:
      - name: Address
        description: "Address information for customers"
        columns:
          - name: city
            description: "City name"
          - name: state
            description: "State or province"
          - name: country
            description: "Country name - lookup based on customer_id via customer_address join"
        meta:
          mapping_rule: "Lookup country based on customer_id"
          notes: "Join customer_address to get address_id and join address to get the country"

      - name: Customer
        description: "Customer master data"
        columns:
          - name: customer_id
            description: "Unique customer identifier"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: phone
            description: "Customer phone number"
          - name: created_ts
            description: "Customer creation timestamp"
        meta:
          mapping_rule: "customer is active only if the created_ts is less than 2 years from current_date"

      - name: Inventory
        description: "Product inventory levels by warehouse"
        columns:
          - name: quantity_on_hand
            description: "Available quantity in stock"
          - name: product_id
            description: "Product identifier"
          - name: warehouse_id
            description: "Warehouse identifier"
        meta:
          mapping_rule: "Direct Mapping"

      - name: Order_Header
        description: "Order header information"
        columns:
          - name: order_date
            description: "Date when order was placed"
          - name: customer_id
            description: "Customer who placed the order"
          - name: order_id
            description: "Unique order identifier"
        meta:
          mapping_rule: "Direct Mapping"

      - name: Order_Line
        description: "Individual line items within orders"
        columns:
          - name: product_id
            description: "Product identifier for the line item"
          - name: order_line_id
            description: "Unique order line identifier"
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Price per unit"
        meta:
          mapping_rule: "Lookup product_id from Order_Line based on order_line_id"

      - name: Payment_Transaction
        description: "Payment transaction records"
        columns:
          - name: order_id
            description: "Associated order identifier"
          - name: payment_method
            description: "Method of payment used"
          - name: amount_paid
            description: "Amount paid in transaction"
          - name: payment_ts
            description: "Payment timestamp"
        meta:
          mapping_rule: "Convert to date"

      - name: Product
        description: "Product master data"
        columns:
          - name: product_id
            description: "Unique product identifier"
          - name: product_name
            description: "Product name"
          - name: brand
            description: "Product brand"
          - name: unit_price
            description: "Base unit price before discounts"
        meta:
          mapping_rule: "Lookup discount_pct from Product_Discount and calculate the discounted price"
          notes: "Consider the discount effective_from and effective_to dates"

      - name: Product_Category
        description: "Product category information"
        columns:
          - name: category_name
            description: "Name of the product category"
        meta:
          mapping_rule: "Lookup category_name based on product_id"

      - name: Returns
        description: "Product return records"
        columns:
          - name: return_date
            description: "Date when product was returned"
          - name: order_line_id
            description: "Order line item being returned"
          - name: return_reason
            description: "Reason for the return"
        meta:
          mapping_rule: "Direct Mapping"

      - name: Shipment
        description: "Order shipment tracking information"
        columns:
          - name: order_id
            description: "Associated order identifier"
          - name: shipped_date
            description: "Date when order was shipped"
          - name: delivery_date
            description: "Date when order was delivered"
          - name: status
            description: "Current shipment status"
        meta:
          mapping_rule: "Direct Mapping"