version: 2

sources:
  - name: dwh_staging
    database: bsl_staging
    schema: dwh_staging
    description: "Staging tables for data warehouse"
    tables:
      - name: address
        description: "Address information including city, state, and country"
        columns:
          - name: city
            description: "City name"
          - name: state
            description: "State or province"
          - name: country
            description: "Country name - lookup based on customer_id via customer_address join"

      - name: customer
        description: "Customer master data with contact information"
        columns:
          - name: customer_id
            description: "Unique customer identifier"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: phone
            description: "Customer phone number"
          - name: created_ts
            description: "Customer creation timestamp - used to determine active status (active if less than 2 years from current date)"

      - name: customer_address
        description: "Junction table linking customers to addresses"

      - name: inventory
        description: "Product inventory levels by warehouse"
        columns:
          - name: quantity_on_hand
            description: "Current inventory quantity"
          - name: product_id
            description: "Product identifier"
          - name: warehouse_id
            description: "Warehouse identifier"

      - name: order_header
        description: "Order header information"
        columns:
          - name: order_date
            description: "Date order was placed"
          - name: customer_id
            description: "Customer who placed the order"
          - name: order_id
            description: "Unique order identifier"

      - name: order_line
        description: "Individual line items within orders"
        columns:
          - name: product_id
            description: "Product identifier for the line item"
          - name: order_line_id
            description: "Unique order line identifier"
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Price per unit"

      - name: payment_transaction
        description: "Payment transactions for orders"
        columns:
          - name: order_id
            description: "Associated order identifier"
          - name: payment_method
            description: "Method of payment used"
          - name: amount_paid
            description: "Amount paid in transaction"
          - name: payment_ts
            description: "Payment timestamp - to be converted to date"

      - name: product
        description: "Product master data"
        columns:
          - name: product_id
            description: "Unique product identifier"
          - name: product_name
            description: "Product name"
          - name: brand
            description: "Product brand"

      - name: product_category
        description: "Product category information"
        columns:
          - name: product_category_id
            description: "Unique product category identifier - used to lookup category_name"

      - name: product_discount
        description: "Product discount information with effective dates"
        columns:
          - name: effective_from
            description: "Discount effective start date"
          - name: effective_to
            description: "Discount effective end date"

      - name: returns
        description: "Product return information"
        columns:
          - name: return_date
            description: "Date of return"
          - name: order_line_id
            description: "Order line being returned"
          - name: return_reason
            description: "Reason for return"

      - name: shipment
        description: "Order shipment tracking information"
        columns:
          - name: order_id
            description: "Associated order identifier"
          - name: shipped_date
            description: "Date order was shipped"
          - name: delivery_date
            description: "Date order was delivered"
          - name: status
            description: "Current shipment status"