version: 2

sources:
  - name: dwh_staging
    database: bsl_staging
    schema: dwh_staging
    description: "Staging tables for data warehouse processing"
    tables:
      - name: address
        description: "Address information for customers"
        columns:
          - name: city
            description: "City name"
          - name: state
            description: "State or province"
          - name: country
            description: "Country name"

      - name: customer
        description: "Customer master data with activity based on creation date"
        columns:
          - name: customer_id
            description: "Unique customer identifier"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: phone
            description: "Customer phone number"
          - name: created_ts
            description: "Customer creation timestamp - used to determine active status"

      - name: customer_address
        description: "Junction table linking customers to addresses"
        columns:
          - name: customer_id
            description: "Reference to customer"
          - name: address_id
            description: "Reference to address"

      - name: inventory
        description: "Product inventory levels by warehouse"
        columns:
          - name: quantity_on_hand
            description: "Available inventory quantity"
          - name: product_id
            description: "Product identifier"
          - name: warehouse_id
            description: "Warehouse identifier"

      - name: order_header
        description: "Order header information"
        columns:
          - name: order_date
            description: "Date order was placed"
          - name: customer_id
            description: "Customer who placed the order"
          - name: order_id
            description: "Unique order identifier"

      - name: order_line
        description: "Individual line items within orders"
        columns:
          - name: product_id
            description: "Product ordered"
          - name: order_line_id
            description: "Unique order line identifier"
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Price per unit"

      - name: payment_transaction
        description: "Payment transactions for orders"
        columns:
          - name: order_id
            description: "Associated order"
          - name: payment_method
            description: "Method of payment"
          - name: amount_paid
            description: "Payment amount"
          - name: payment_ts
            description: "Payment timestamp"

      - name: product
        description: "Product master data with discount calculations"
        columns:
          - name: product_id
            description: "Unique product identifier"
          - name: product_name
            description: "Product name"
          - name: brand
            description: "Product brand"
          - name: unit_price
            description: "Base unit price before discounts"

      - name: product_category
        description: "Product category information"
        columns:
          - name: product_id
            description: "Product identifier"
          - name: category_name
            description: "Category name"

      - name: product_discount
        description: "Product discount information with effective dates"
        columns:
          - name: product_id
            description: "Product identifier"
          - name: discount_pct
            description: "Discount percentage"
          - name: effective_from
            description: "Discount effective start date"
          - name: effective_to
            description: "Discount effective end date"

      - name: returns
        description: "Product return information"
        columns:
          - name: return_date
            description: "Date of return"
          - name: order_line_id
            description: "Order line being returned"
          - name: return_reason
            description: "Reason for return"

      - name: shipment
        description: "Order shipment tracking information"
        columns:
          - name: order_id
            description: "Associated order"
          - name: shipped_date
            description: "Date order was shipped"
          - name: delivery_date
            description: "Date order was delivered"
          - name: status
            description: "Shipment status"