version: 2

sources:
  - name: dwh_raw
    database: bsl_raw
    schema: dwh_raw
    description: "Raw data source tables from the data warehouse"
    tables:
      - name: addresses
        description: "Customer address information"
        columns:
          - name: address_id
            description: "Unique identifier for address"
          - name: customer_id
            description: "Reference to customer"
          - name: address_line1
            description: "Primary address line"
          - name: city
            description: "City name"
          - name: country
            description: "Country name"
          - name: inserted_at
            description: "Record insertion timestamp"

      - name: categories
        description: "Product category hierarchy"
        columns:
          - name: category_id
            description: "Unique identifier for category"
          - name: category_name
            description: "Category name"
          - name: parent_category_id
            description: "Reference to parent category"
          - name: is_active
            description: "Category active status flag"

      - name: customers
        description: "Customer master data"
        columns:
          - name: customer_id
            description: "Unique identifier for customer"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: inserted_at
            description: "Record insertion timestamp"

      - name: inventory
        description: "Product inventory levels"
        columns:
          - name: product_id
            description: "Reference to product"
          - name: supplier_id
            description: "Reference to supplier"
          - name: stock_qty
            description: "Current stock quantity"
          - name: warehouse_location
            description: "Warehouse location identifier"
          - name: last_updated
            description: "Last inventory update timestamp"

      - name: order_items
        description: "Individual items within orders"
        columns:
          - name: order_id
            description: "Reference to order"
          - name: product_id
            description: "Reference to product"
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Price per unit"
          - name: order_item_id
            description: "Unique identifier for order item"

      - name: orders
        description: "Customer orders"
        columns:
          - name: order_id
            description: "Unique identifier for order"
          - name: customer_id
            description: "Reference to customer"
          - name: order_date
            description: "Date order was placed"
          - name: status
            description: "Current order status"
          - name: total_amount
            description: "Total order amount"

      - name: payments
        description: "Payment transactions"
        columns:
          - name: payment_id
            description: "Unique identifier for payment"
          - name: order_id
            description: "Reference to order"
          - name: payment_date
            description: "Date payment was processed"
          - name: payment_method
            description: "Payment method used"
          - name: amount
            description: "Payment amount"

      - name: products
        description: "Product catalog"
        columns:
          - name: product_id
            description: "Unique identifier for product"
          - name: product_name
            description: "Product name"
          - name: price
            description: "Product price"

      - name: shipments
        description: "Order shipment information"
        columns:
          - name: shipment_id
            description: "Unique identifier for shipment"
          - name: order_id
            description: "Reference to order"
          - name: shipment_date
            description: "Date shipment was sent"
          - name: carrier
            description: "Shipping carrier"
          - name: tracking_number
            description: "Shipment tracking number"

      - name: suppliers
        description: "Supplier information"
        columns:
          - name: supplier_id
            description: "Unique identifier for supplier"
          - name: supplier_name
            description: "Supplier company name"
          - name: contact_email
            description: "Supplier contact email"
          - name: country
            description: "Supplier country"
          - name: active_flag
            description: "Supplier active status flag"