version: 2

sources:
  - name: dwh_raw
    description: Raw data warehouse tables from BSL_RAW database
    database: BSL_RAW
    schema: DWH_RAW
    tables:
      - name: addresses
        description: Customer address information
        columns:
          - name: address_id
            description: Unique identifier for address
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customers table
            tests:
              - not_null
          - name: address_line1
            description: Primary address line
          - name: city
            description: City name
          - name: country
            description: Country name
          - name: inserted_at
            description: Timestamp when record was inserted

      - name: categories
        description: Product category hierarchy
        columns:
          - name: category_id
            description: Unique identifier for category
            tests:
              - unique
              - not_null
          - name: category_name
            description: Name of the category
          - name: parent_category_id
            description: Parent category for hierarchical structure
          - name: is_active
            description: Flag indicating if category is active

      - name: customers
        description: Customer master data
        columns:
          - name: customer_id
            description: Unique identifier for customer
            tests:
              - unique
              - not_null
          - name: first_name
            description: Customer first name
          - name: last_name
            description: Customer last name
          - name: email
            description: Customer email address
          - name: inserted_at
            description: Timestamp when record was inserted

      - name: inventory
        description: Product inventory levels by supplier and location
        columns:
          - name: product_id
            description: Foreign key to products table
            tests:
              - not_null
          - name: supplier_id
            description: Foreign key to suppliers table
            tests:
              - not_null
          - name: stock_qty
            description: Current stock quantity
          - name: warehouse_location
            description: Warehouse location identifier
          - name: last_updated
            description: Timestamp when inventory was last updated

      - name: orders
        description: Customer order header information
        columns:
          - name: order_id
            description: Unique identifier for order
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customers table
            tests:
              - not_null
          - name: order_date
            description: Date when order was placed
          - name: status
            description: Current order status
          - name: total_amount
            description: Total order amount

      - name: order_items
        description: Individual items within orders
        columns:
          - name: order_item_id
            description: Unique identifier for order item
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders table
            tests:
              - not_null
          - name: product_id
            description: Foreign key to products table
            tests:
              - not_null
          - name: quantity
            description: Quantity of product ordered
          - name: unit_price
            description: Price per unit at time of order

      - name: payments
        description: Payment transactions for orders
        columns:
          - name: payment_id
            description: Unique identifier for payment
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders table
            tests:
              - not_null
          - name: payment_date
            description: Date when payment was processed
          - name: payment_method
            description: Method of payment used
          - name: amount
            description: Payment amount

      - name: products
        description: Product master data
        columns:
          - name: product_id
            description: Unique identifier for product
            tests:
              - unique
              - not_null
          - name: product_name
            description: Name of the product
          - name: category_id
            description: Foreign key to categories table
          - name: price
            description: Product price

      - name: shipments
        description: Order shipment tracking information
        columns:
          - name: shipment_id
            description: Unique identifier for shipment
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders table
            tests:
              - not_null
          - name: shipped_date
            description: Date when order was shipped
          - name: carrier
            description: Shipping carrier name
          - name: tracking_number
            description: Shipment tracking number

      - name: suppliers
        description: Supplier master data
        columns:
          - name: supplier_id
            description: Unique identifier for supplier
            tests:
              - unique
              - not_null
          - name: supplier_name
            description: Name of the supplier
          - name: contact_email
            description: Supplier contact email
          - name: country
            description: Supplier country
          - name: active_flag
            description: Flag indicating if supplier is active