version: 2
sources:
- name: dwh_raw
  database: bsl_raw
  schema: dwh_raw
  description: Raw data warehouse schema containing transactional and master data from various business systems
  tables:
  - name: addresses
    description: Customer address information with geographical details
    columns:
    - name: address_id
      description: Unique identifier for each address record
    - name: customer_id
      description: Foreign key reference to customers table
    - name: address_line1
      description: Primary address line containing street information
    - name: city
      description: City name where the address is located
    - name: country
      description: Country where the address is located
    - name: inserted_at
      description: Timestamp when the address record was created
  - name: categories
    description: Product category hierarchy with parent-child relationships
    columns:
    - name: category_id
      description: Unique identifier for each product category
    - name: category_name
      description: Display name of the product category
    - name: parent_category_id
      description: Reference to parent category for hierarchical structure
    - name: is_active
      description: Flag indicating if the category is currently active
  - name: customers
    description: Customer master data containing personal information
    columns:
    - name: customer_id
      description: Unique identifier for each customer
    - name: first_name
      description: Customer's first name
    - name: last_name
      description: Customer's last name
    - name: email
      description: Customer's email address
    - name: inserted_at
      description: Timestamp when the customer record was created
  - name: inventory
    description: Product inventory levels by supplier and warehouse location
    columns:
    - name: product_id
      description: Foreign key reference to products table
    - name: supplier_id
      description: Foreign key reference to suppliers table
    - name: stock_qty
      description: Current quantity of product in stock
    - name: warehouse_location
      description: Physical location where inventory is stored
    - name: last_updated
      description: Timestamp of last inventory update
  - name: order_items
    description: Individual line items within customer orders
    columns:
    - name: order_item_id
      description: Unique identifier for each order line item
    - name: order_id
      description: Foreign key reference to orders table
    - name: product_id
      description: Foreign key reference to products table
    - name: quantity
      description: Number of units ordered for this line item
    - name: unit_price
      description: Price per unit for the product
  - name: orders
    description: Customer order header information with status and totals
    columns:
    - name: order_id
      description: Unique identifier for each customer order
    - name: customer_id
      description: Foreign key reference to customers table
    - name: order_date
      description: Date when the order was placed
    - name: status
      description: Current status of the order
    - name: total_amount
      description: Total monetary value of the order
  - name: payments
    description: Payment transactions associated with customer orders
    columns:
    - name: payment_id
      description: Unique identifier for each payment transaction
    - name: order_id
      description: Foreign key reference to orders table
    - name: payment_date
      description: Date when the payment was processed
    - name: payment_method
      description: Method used for payment processing
    - name: amount
      description: Monetary amount of the payment
  - name: products
    description: Product master data with pricing information
    columns:
    - name: product_id
      description: Unique identifier for each product
    - name: product_name
      description: Display name of the product
    - name: price
      description: Current selling price of the product
  - name: shipments
    description: Shipping information for fulfilled orders
    columns:
    - name: shipment_id
      description: Unique identifier for each shipment
    - name: order_id
      description: Foreign key reference to orders table
    - name: shipped_date
      description: Date when the order was shipped
    - name: carrier
      description: Shipping company handling the delivery
    - name: tracking_number
      description: Carrier-provided tracking identifier
  - name: suppliers
    description: Supplier master data with contact and status information
    columns:
    - name: supplier_id
      description: Unique identifier for each supplier
    - name: supplier_name
      description: Business name of the supplier
    - name: contact_email
      description: Primary email contact for the supplier
    - name: country
      description: Country where the supplier is located
    - name: active_flag
      description: Flag indicating if the supplier is currently active