import streamlit as st
import os
import threading
import http.server
import socketserver
from functools import partial
import webbrowser
from style_utils import apply_style, render_header

apply_style()
render_header()

# --- Streamlit Page Setup ---
st.set_page_config(page_title="DBT Docs Viewer", layout="wide")
st.title("📊 DBT Lineage Graph Viewer (New Tab Version)")

st.markdown("""
Upload the three files generated by **`dbt docs generate`** —
`index.html`, `manifest.json`, and `catalog.json` — then click **Submit** to open your dbt docs in a new window.
""")

# --- Persistent Cache Directory ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DBT_DOCS_DIR = os.path.join(BASE_DIR, "dbt_docs_cache")
os.makedirs(DBT_DOCS_DIR, exist_ok=True)

# --- Initialize Session State ---
if "server_thread" not in st.session_state:
    st.session_state.server_thread = None
if "files_uploaded" not in st.session_state:
    st.session_state.files_uploaded = False
if "server_port" not in st.session_state:
    st.session_state.server_port = 8505

PORT = st.session_state.server_port


# --- Function to run HTTP server (without changing directory) ---
def run_server(directory, port):
    handler = partial(http.server.SimpleHTTPRequestHandler, directory=directory)
    with socketserver.TCPServer(("", port), handler) as httpd:
        httpd.serve_forever()


# --- Re-upload Button ---
st.markdown("#### ⚙️ Manage Uploaded Files")
if st.session_state.files_uploaded:
    if st.button("🔁 Re-upload files"):
        st.session_state.files_uploaded = False
        for f in ["index.html", "catalog.json", "manifest.json"]:
            try:
                os.remove(os.path.join(DBT_DOCS_DIR, f))
            except FileNotFoundError:
                pass
        st.success("Cleared uploaded files. You can upload new files now.")
        st.stop()

# --- File Upload Section ---
col1, col2, col3 = st.columns(3)
with col1:
    index_file = st.file_uploader("Upload index.html", type=["html"])
with col2:
    catalog_file = st.file_uploader("Upload catalog.json", type=["json"])
with col3:
    manifest_file = st.file_uploader("Upload manifest.json", type=["json"])

# --- Submit Button ---
submit_clicked = st.button("🚀 Submit and Open DBT Docs")

if submit_clicked:
    if not (index_file and catalog_file and manifest_file):
        st.error("Please upload all three files before submitting.")
        st.stop()

    # Save uploaded files to persistent folder
    index_path = os.path.join(DBT_DOCS_DIR, "index.html")
    catalog_path = os.path.join(DBT_DOCS_DIR, "catalog.json")
    manifest_path = os.path.join(DBT_DOCS_DIR, "manifest.json")

    with open(index_path, "wb") as f:
        f.write(index_file.getbuffer())
    with open(catalog_path, "wb") as f:
        f.write(catalog_file.getbuffer())
    with open(manifest_path, "wb") as f:
        f.write(manifest_file.getbuffer())

    st.session_state.files_uploaded = True

    # Start server once per session
    if st.session_state.server_thread is None:
        thread = threading.Thread(target=run_server, args=(DBT_DOCS_DIR, PORT), daemon=True)
        thread.start()
        st.session_state.server_thread = thread
        st.success(f"✅ Local server started on port {PORT}")

    # Open dbt docs in a new browser tab/window
    docs_url = f"http://localhost:{PORT}/index.html"
    webbrowser.open_new_tab(docs_url)

    st.success(f"DBT Docs launched successfully! 🎉 [Open Manually]({docs_url})")

elif st.session_state.files_uploaded:
    st.info(f"✅ Using previously uploaded files. [Open DBT Docs](http://localhost:{PORT}/index.html)")
