import streamlit as st
import pandas as pd
import yaml
import os
import zipfile
from jinja2 import Environment, FileSystemLoader
import io
import json
from snowflake.snowpark import Session
from snowflake.cortex import Complete, CompleteOptions
import re

# --- 1. Connect to Snowflake ---
connection_parameters = {
    "user": "SHAJAHAN",
    "password": "Shajahan@snowflake_2002",
    "account": "DTJCYHT-WGB03396",
    "role": "ACCOUNTADMIN",
    "warehouse": "COMPUTE_WH",
    "database": "DATASET",
    "schema": "PUBLIC",
}

options = CompleteOptions(
    temperature=0.2,
    max_tokens=4096,
    guardrails=False
)
session = Session.builder.configs(connection_parameters).create() 

model_summary =  ['Model: customers\nSchema: staging\nColumns:\ncust_id → customer_id (STRING) | logic: direct mapping\nfirst_name → full_name (STRING) | logic: concatenate first_name and last_name\nsignup_date → signup_month (STRING) | logic: extract month name from signup_date\nis_vip_flag → is_vip (BOOLEAN) | logic: convert Y/N to TRUE/FALSE', 'Model: employees\nSchema: staging\nColumns:\nemp_id → employee_id (STRING) | logic: direct mapping\nsalary → annual_bonus (FLOAT) | logic: calculate 15% of salary as annual bonus', "Model: inventory_summary\nSchema: staging\nColumns:\nproduct_id → product_id (STRING) | logic: direct mapping\nquantity → stock_status (STRING) | logic: if quantity > 0 then 'IN_STOCK' else 'OUT_OF_STOCK'", 'Model: orders\nSchema: staging\nColumns:\norder_id → order_id (STRING) | logic: direct mapping\ncustomer_id → customer_id (STRING) | logic: direct mapping\norder_date → order_week (STRING) | logic: derive ISO week from order_date\ntotal_amount → total_amount_usd (FLOAT) | logic: convert from inr to usd', "Model: payments\nSchema: staging\nColumns:\npayment_id → payment_id (STRING) | logic: direct mapping\npayment_mode → payment_category (STRING) | logic: categorize as 'Card','Wallet','Cash' based on payment_mode value", "Model: products\nSchema: staging\nColumns:\nproduct_id → product_id (STRING) | logic: direct mapping\nprice → discounted_price (FLOAT) | logic: apply 10% discount if category = 'Seasonal'", "Model: reviews\nSchema: staging\nColumns:\nreview_id → review_id (STRING) | logic: direct mapping\nrating → sentiment_category (STRING) | logic: if rating >= 4 then 'Positive' elif rating = 3 then 'Neutral' else 'Negative'", 'Model: shipments\nSchema: staging\nColumns:\nshipment_id → shipment_id (STRING) | logic: direct mapping\ndelivery_date → delivery_delay_days (INTEGER) | logic: calculate difference between delivery_date and order_date', 'Model: transactions\nSchema: staging\nColumns:\ntransaction_id → transaction_id (STRING) | logic: direct mapping\namount → amount_with_tax (FLOAT) | logic: add 18% GST to amount', "Model: web_sessions\nSchema: staging\nColumns:\nsession_id → session_id (STRING) | logic: direct mapping\ntimestamp → session_hour (INTEGER) | logic: extract hour from timestamp\nurl → domain_name (STRING) | logic: extract domain from url using string split on '/'"]
schema_prompt = f"""
        You are a Snowflake + dbt expert.

        Generate one valid dbt **schema.yml** file for the following models.
            - Describe the model `{{t_table}}` with columns, descriptions, and dbt tests.
            - Follow dbt YAML structure starting with `version: 2` and `models:`.
            - Use only valid YAML (no markdown formatting).
            - Don't repeat the words like `version` or `models`.
            - Use proper intendation
            - Don't skip anything. Give full code.
            - Don't add schema name and type.

        The generated yaml file should look like this:
        version: 2
        models:
          - name: {{ model_name }}
            columns:
              - name: {{column1}}
                tests:
                - {{tests}}
                description: {{description}}

        Models:
        {chr(10).join(model_summary)}

        Output YAML only — no markdown, no code fences, no prose.
        """

schema_result = Complete(model="claude-4-sonnet", prompt=schema_prompt, session=session, options=options,)
schema_text = schema_result.get("response") if isinstance(schema_result, dict) else str(schema_result)
schema_text = re.sub(r"(?i)^sure.*|^here.*|```.*", "", schema_text).strip()

schema_yml_path = "models/schema.yml"
with open(schema_yml_path, "w", encoding="utf-8") as f:
    f.write(schema_text)

print(f"✅ Final consolidated schema.yml generated: {schema_yml_path}")
st.write("✅ Final consolidated `schema.yml` generated by Cortex AI")
