version: 2

sources:
  - name: raw
    database: demo_db
    schema: raw
    tables:
      - name: raw_customers
        description: Raw data table for customer information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_employees
        description: Raw data table for employee information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_inventory
        description: Raw data table for inventory information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_orders
        description: Raw data table for order information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_payments
        description: Raw data table for payment information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_products
        description: Raw data table for product information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_reviews
        description: Raw data table for product reviews
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_shipments
        description: Raw data table for shipment information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_transactions
        description: Raw data table for transaction information
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_web_logs
        description: Raw data table for web logs
        columns:
          - name: id
            tests:
              - unique
              - not_null