version: 2

sources:
  - name: raw_customers
    database: demo_db
    schema: raw
    tables:
      - name: raw_customers
        columns:
          - name: cust_id
            tests:
              - not_null
              - unique
          - name: first_name
            tests:
              - not_null
          - name: signup_date
            tests:
              - not_null
          - name: is_vip_flag
            tests:
              - not_null

  - name: raw_employees
    database: demo_db
    schema: raw
    tables:
      - name: raw_employees
        columns:
          - name: emp_id
            tests:
              - not_null
              - unique
          - name: salary
            tests:
              - not_null

  - name: raw_inventory
    database: demo_db
    schema: raw
    tables:
      - name: raw_inventory
        columns:
          - name: product_id
            tests:
              - not_null
              - unique
          - name: quantity
            tests:
              - not_null

  - name: raw_orders
    database: demo_db
    schema: raw
    tables:
      - name: raw_orders
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: customer_id
            tests:
              - not_null
          - name: order_date
            tests:
              - not_null
          - name: total_amount
            tests:
              - not_null

  - name: raw_payments
    database: demo_db
    schema: raw
    tables:
      - name: raw_payments
        columns:
          - name: payment_id
            tests:
              - not_null
              - unique
          - name: payment_mode
            tests:
              - not_null

  - name: raw_products
    database: demo_db
    schema: raw
    tables:
      - name: raw_products
        columns:
          - name: product_id
            tests:
              - not_null
              - unique
          - name: price
            tests:
              - not_null

  - name: raw_reviews
    database: demo_db
    schema: raw
    tables:
      - name: raw_reviews
        columns:
          - name: review_id
            tests:
              - not_null
              - unique
          - name: rating
            tests:
              - not_null

  - name: raw_shipments
    database: demo_db
    schema: raw
    tables:
      - name: raw_shipments
        columns:
          - name: shipment_id
            tests:
              - not_null
              - unique
          - name: delivery_date
            tests:
              - not_null

  - name: raw_transactions
    database: demo_db
    schema: raw
    tables:
      - name: raw_transactions
        columns:
          - name: transaction_id
            tests:
              - not_null
              - unique
          - name: amount
            tests:
              - not_null

  - name: raw_web_logs